// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: TBoxBase
type TBoxBase struct {

	//DropBox
	DropBox []*DropBoxDefine
}

// Defined in table: DropBox
type DropBoxDefine struct {

	//id
	Id uint32 `json:"id"`

	//宝箱图片路径
	BoxPath string

	//奖励类型(1 金币 2 体力 3 侍女 4 道具 5 小游戏事件)
	Type uint32

	//道具id
	RewardId uint32

	//奖励值
	Value uint32

	//生成间隔(为0表示不是时间间隔掉落)
	Interval uint32

	//生成的关卡
	Level uint32
}

// 添加init初始实例 "Add By Tse"
var InsTBoxBaseTable *TBoxBaseTable

func init() {
	InsTBoxBaseTable = NewTBoxBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *TBoxBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// TBoxBase 访问接口
type TBoxBaseTable struct {

	// 表格原始数据
	TBoxBase

	// 索引函数表
	indexFuncByName map[string][]func(*TBoxBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*TBoxBaseTable) error

	// 加载前回调
	preFuncList []func(*TBoxBaseTable) error

	// 加载后回调
	postFuncList []func(*TBoxBaseTable) error

	DropBoxById map[uint32]*DropBoxDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *TBoxBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab TBoxBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.TBoxBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *TBoxBaseTable) RegisterIndexEntry(name string, indexCallback func(*TBoxBaseTable) error, clearCallback func(*TBoxBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *TBoxBaseTable) RegisterPreEntry(callback func(*TBoxBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *TBoxBaseTable) RegisterPostEntry(callback func(*TBoxBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个TBoxBase表读取实例
func NewTBoxBaseTable() *TBoxBaseTable {
	return &TBoxBaseTable{

		indexFuncByName: map[string][]func(*TBoxBaseTable) error{

			"DropBox": {func(tab *TBoxBaseTable) error {

				// DropBox
				for _, def := range tab.DropBox {

					if _, ok := tab.DropBoxById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in DropBoxById: %v", def.Id))
					}

					tab.DropBoxById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*TBoxBaseTable) error{

			"DropBox": {func(tab *TBoxBaseTable) error {

				// DropBox

				tab.DropBoxById = make(map[uint32]*DropBoxDefine)

				return nil
			}},
		},

		DropBoxById: make(map[uint32]*DropBoxDefine),
	}
}
