// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: TDateEventBase
type TDateEventBase struct {

	//DateEvent
	DateEvent []*DateEventDefine
}

// Defined in table: DateEvent
type DateEventDefine struct {

	//唯一id
	Id uint32 `json:"id"`

	//类型（1时间，2地点，3事件）
	Datetype uint32

	//约会的id
	DateId uint32

	//头像
	Datepath string

	//名字
	DateName string
}

// 添加init初始实例 "Add By Tse"
var InsTDateEventBaseTable *TDateEventBaseTable

func init() {
	InsTDateEventBaseTable = NewTDateEventBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *TDateEventBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// TDateEventBase 访问接口
type TDateEventBaseTable struct {

	// 表格原始数据
	TDateEventBase

	// 索引函数表
	indexFuncByName map[string][]func(*TDateEventBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*TDateEventBaseTable) error

	// 加载前回调
	preFuncList []func(*TDateEventBaseTable) error

	// 加载后回调
	postFuncList []func(*TDateEventBaseTable) error

	DateEventById map[uint32]*DateEventDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *TDateEventBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab TDateEventBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.TDateEventBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *TDateEventBaseTable) RegisterIndexEntry(name string, indexCallback func(*TDateEventBaseTable) error, clearCallback func(*TDateEventBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *TDateEventBaseTable) RegisterPreEntry(callback func(*TDateEventBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *TDateEventBaseTable) RegisterPostEntry(callback func(*TDateEventBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个TDateEventBase表读取实例
func NewTDateEventBaseTable() *TDateEventBaseTable {
	return &TDateEventBaseTable{

		indexFuncByName: map[string][]func(*TDateEventBaseTable) error{

			"DateEvent": {func(tab *TDateEventBaseTable) error {

				// DateEvent
				for _, def := range tab.DateEvent {

					if _, ok := tab.DateEventById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in DateEventById: %v", def.Id))
					}

					tab.DateEventById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*TDateEventBaseTable) error{

			"DateEvent": {func(tab *TDateEventBaseTable) error {

				// DateEvent

				tab.DateEventById = make(map[uint32]*DateEventDefine)

				return nil
			}},
		},

		DateEventById: make(map[uint32]*DateEventDefine),
	}
}
