// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: TDialogueBase
type TDialogueBase struct {

	//TDialogue
	TDialogue []*TDialogueDefine
}

// Defined in table: TDialogue
type TDialogueDefine struct {

	//唯一id
	Id uint32 `json:"id"`

	//对话的id
	Index uint32

	//头像
	HeadSprite []string

	//头像位置 1左 2右
	HeadLocation []uint32

	//名字
	Name string

	//名字位置 1左 2右
	NameLocation uint32

	//对话内容
	Content string
}

// 添加init初始实例 "Add By Tse"
var InsTDialogueBaseTable *TDialogueBaseTable

func init() {
	InsTDialogueBaseTable = NewTDialogueBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *TDialogueBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// TDialogueBase 访问接口
type TDialogueBaseTable struct {

	// 表格原始数据
	TDialogueBase

	// 索引函数表
	indexFuncByName map[string][]func(*TDialogueBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*TDialogueBaseTable) error

	// 加载前回调
	preFuncList []func(*TDialogueBaseTable) error

	// 加载后回调
	postFuncList []func(*TDialogueBaseTable) error

	TDialogueById map[uint32]*TDialogueDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *TDialogueBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab TDialogueBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.TDialogueBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *TDialogueBaseTable) RegisterIndexEntry(name string, indexCallback func(*TDialogueBaseTable) error, clearCallback func(*TDialogueBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *TDialogueBaseTable) RegisterPreEntry(callback func(*TDialogueBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *TDialogueBaseTable) RegisterPostEntry(callback func(*TDialogueBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个TDialogueBase表读取实例
func NewTDialogueBaseTable() *TDialogueBaseTable {
	return &TDialogueBaseTable{

		indexFuncByName: map[string][]func(*TDialogueBaseTable) error{

			"TDialogue": {func(tab *TDialogueBaseTable) error {

				// TDialogue
				for _, def := range tab.TDialogue {

					if _, ok := tab.TDialogueById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in TDialogueById: %v", def.Id))
					}

					tab.TDialogueById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*TDialogueBaseTable) error{

			"TDialogue": {func(tab *TDialogueBaseTable) error {

				// TDialogue

				tab.TDialogueById = make(map[uint32]*TDialogueDefine)

				return nil
			}},
		},

		TDialogueById: make(map[uint32]*TDialogueDefine),
	}
}
