// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: TFunctionOpen
type TFunctionOpen struct {

	//FunctionOpen
	FunctionOpen []*FunctionOpenDefine
}

// Defined in table: FunctionOpen
type FunctionOpenDefine struct {

	//id
	Id uint32 `json:"id"`

	//名字
	Function string

	//开启关卡ID
	OpenLevels int32

	//开启类型1引导 2关卡
	OpenType int32
}

// 添加init初始实例 "Add By Tse"
var InsTFunctionOpenTable *TFunctionOpenTable

func init() {
	InsTFunctionOpenTable = NewTFunctionOpenTable()
}

// 添加Reload方法 "Add By Tse"
func (self *TFunctionOpenTable) Reload() error {
	return self.Load(self.configfile)
}

// TFunctionOpen 访问接口
type TFunctionOpenTable struct {

	// 表格原始数据
	TFunctionOpen

	// 索引函数表
	indexFuncByName map[string][]func(*TFunctionOpenTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*TFunctionOpenTable) error

	// 加载前回调
	preFuncList []func(*TFunctionOpenTable) error

	// 加载后回调
	postFuncList []func(*TFunctionOpenTable) error

	FunctionOpenById map[uint32]*FunctionOpenDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *TFunctionOpenTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab TFunctionOpen

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.TFunctionOpen = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *TFunctionOpenTable) RegisterIndexEntry(name string, indexCallback func(*TFunctionOpenTable) error, clearCallback func(*TFunctionOpenTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *TFunctionOpenTable) RegisterPreEntry(callback func(*TFunctionOpenTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *TFunctionOpenTable) RegisterPostEntry(callback func(*TFunctionOpenTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个TFunctionOpen表读取实例
func NewTFunctionOpenTable() *TFunctionOpenTable {
	return &TFunctionOpenTable{

		indexFuncByName: map[string][]func(*TFunctionOpenTable) error{

			"FunctionOpen": {func(tab *TFunctionOpenTable) error {

				// FunctionOpen
				for _, def := range tab.FunctionOpen {

					if _, ok := tab.FunctionOpenById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in FunctionOpenById: %v", def.Id))
					}

					tab.FunctionOpenById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*TFunctionOpenTable) error{

			"FunctionOpen": {func(tab *TFunctionOpenTable) error {

				// FunctionOpen

				tab.FunctionOpenById = make(map[uint32]*FunctionOpenDefine)

				return nil
			}},
		},

		FunctionOpenById: make(map[uint32]*FunctionOpenDefine),
	}
}
