// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: GiftProBase
type GiftProBase struct {

	//TGiftPro
	TGiftPro []*TGiftProDefine
}

// Defined in table: TGiftPro
type TGiftProDefine struct {

	//ID
	Id uint32 `json:"id"`

	//消费最小值
	Limitmin uint32

	//消费最大值
	Limitmax uint32

	//概率万分比gift表物品ID-概率
	Pro []string
}

// 添加init初始实例 "Add By Tse"
var InsGiftProBaseTable *GiftProBaseTable

func init() {
	InsGiftProBaseTable = NewGiftProBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *GiftProBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// GiftProBase 访问接口
type GiftProBaseTable struct {

	// 表格原始数据
	GiftProBase

	// 索引函数表
	indexFuncByName map[string][]func(*GiftProBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*GiftProBaseTable) error

	// 加载前回调
	preFuncList []func(*GiftProBaseTable) error

	// 加载后回调
	postFuncList []func(*GiftProBaseTable) error

	TGiftProById map[uint32]*TGiftProDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *GiftProBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab GiftProBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.GiftProBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *GiftProBaseTable) RegisterIndexEntry(name string, indexCallback func(*GiftProBaseTable) error, clearCallback func(*GiftProBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *GiftProBaseTable) RegisterPreEntry(callback func(*GiftProBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *GiftProBaseTable) RegisterPostEntry(callback func(*GiftProBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个GiftProBase表读取实例
func NewGiftProBaseTable() *GiftProBaseTable {
	return &GiftProBaseTable{

		indexFuncByName: map[string][]func(*GiftProBaseTable) error{

			"TGiftPro": {func(tab *GiftProBaseTable) error {

				// TGiftPro
				for _, def := range tab.TGiftPro {

					if _, ok := tab.TGiftProById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in TGiftProById: %v", def.Id))
					}

					tab.TGiftProById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*GiftProBaseTable) error{

			"TGiftPro": {func(tab *GiftProBaseTable) error {

				// TGiftPro

				tab.TGiftProById = make(map[uint32]*TGiftProDefine)

				return nil
			}},
		},

		TGiftProById: make(map[uint32]*TGiftProDefine),
	}
}
