// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: TGoldRewardRatioBase
type TGoldRewardRatioBase struct {

	//GoldRewardRatio
	GoldRewardRatio []*GoldRewardRatioDefine
}

// Defined in table: GoldRewardRatio
type GoldRewardRatioDefine struct {

	//id
	Id uint32 `json:"id"`

	//关卡对应的系数
	RatioByLevel []string
}

// 添加init初始实例 "Add By Tse"
var InsTGoldRewardRatioBaseTable *TGoldRewardRatioBaseTable

func init() {
	InsTGoldRewardRatioBaseTable = NewTGoldRewardRatioBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *TGoldRewardRatioBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// TGoldRewardRatioBase 访问接口
type TGoldRewardRatioBaseTable struct {

	// 表格原始数据
	TGoldRewardRatioBase

	// 索引函数表
	indexFuncByName map[string][]func(*TGoldRewardRatioBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*TGoldRewardRatioBaseTable) error

	// 加载前回调
	preFuncList []func(*TGoldRewardRatioBaseTable) error

	// 加载后回调
	postFuncList []func(*TGoldRewardRatioBaseTable) error

	GoldRewardRatioById map[uint32]*GoldRewardRatioDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *TGoldRewardRatioBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab TGoldRewardRatioBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.TGoldRewardRatioBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *TGoldRewardRatioBaseTable) RegisterIndexEntry(name string, indexCallback func(*TGoldRewardRatioBaseTable) error, clearCallback func(*TGoldRewardRatioBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *TGoldRewardRatioBaseTable) RegisterPreEntry(callback func(*TGoldRewardRatioBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *TGoldRewardRatioBaseTable) RegisterPostEntry(callback func(*TGoldRewardRatioBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个TGoldRewardRatioBase表读取实例
func NewTGoldRewardRatioBaseTable() *TGoldRewardRatioBaseTable {
	return &TGoldRewardRatioBaseTable{

		indexFuncByName: map[string][]func(*TGoldRewardRatioBaseTable) error{

			"GoldRewardRatio": {func(tab *TGoldRewardRatioBaseTable) error {

				// GoldRewardRatio
				for _, def := range tab.GoldRewardRatio {

					if _, ok := tab.GoldRewardRatioById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in GoldRewardRatioById: %v", def.Id))
					}

					tab.GoldRewardRatioById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*TGoldRewardRatioBaseTable) error{

			"GoldRewardRatio": {func(tab *TGoldRewardRatioBaseTable) error {

				// GoldRewardRatio

				tab.GoldRewardRatioById = make(map[uint32]*GoldRewardRatioDefine)

				return nil
			}},
		},

		GoldRewardRatioById: make(map[uint32]*GoldRewardRatioDefine),
	}
}
