// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: THeadBase
type THeadBase struct {

	//Head
	Head []*HeadDefine
}

// Defined in table: Head
type HeadDefine struct {

	//id
	Id uint32 `json:"id"`

	//头像图片
	HeadPath string

	//名字
	Name string
}

// 添加init初始实例 "Add By Tse"
var InsTHeadBaseTable *THeadBaseTable

func init() {
	InsTHeadBaseTable = NewTHeadBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *THeadBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// THeadBase 访问接口
type THeadBaseTable struct {

	// 表格原始数据
	THeadBase

	// 索引函数表
	indexFuncByName map[string][]func(*THeadBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*THeadBaseTable) error

	// 加载前回调
	preFuncList []func(*THeadBaseTable) error

	// 加载后回调
	postFuncList []func(*THeadBaseTable) error

	HeadById map[uint32]*HeadDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *THeadBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab THeadBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.THeadBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *THeadBaseTable) RegisterIndexEntry(name string, indexCallback func(*THeadBaseTable) error, clearCallback func(*THeadBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *THeadBaseTable) RegisterPreEntry(callback func(*THeadBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *THeadBaseTable) RegisterPostEntry(callback func(*THeadBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个THeadBase表读取实例
func NewTHeadBaseTable() *THeadBaseTable {
	return &THeadBaseTable{

		indexFuncByName: map[string][]func(*THeadBaseTable) error{

			"Head": {func(tab *THeadBaseTable) error {

				// Head
				for _, def := range tab.Head {

					if _, ok := tab.HeadById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in HeadById: %v", def.Id))
					}

					tab.HeadById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*THeadBaseTable) error{

			"Head": {func(tab *THeadBaseTable) error {

				// Head

				tab.HeadById = make(map[uint32]*HeadDefine)

				return nil
			}},
		},

		HeadById: make(map[uint32]*HeadDefine),
	}
}
