// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: LevelBasee
type LevelBasee struct {

	//TLevel
	TLevel []*TLevelDefine
}

// Defined in table: TLevel
type TLevelDefine struct {

	//id
	Id uint32 `json:"id"`

	//经验
	ExpNums int32

	//奖励
	Reward int32
}

// 添加init初始实例 "Add By Tse"
var InsLevelBaseeTable *LevelBaseeTable

func init() {
	InsLevelBaseeTable = NewLevelBaseeTable()
}

// 添加Reload方法 "Add By Tse"
func (self *LevelBaseeTable) Reload() error {
	return self.Load(self.configfile)
}

// LevelBasee 访问接口
type LevelBaseeTable struct {

	// 表格原始数据
	LevelBasee

	// 索引函数表
	indexFuncByName map[string][]func(*LevelBaseeTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*LevelBaseeTable) error

	// 加载前回调
	preFuncList []func(*LevelBaseeTable) error

	// 加载后回调
	postFuncList []func(*LevelBaseeTable) error

	TLevelById map[uint32]*TLevelDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *LevelBaseeTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab LevelBasee

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.LevelBasee = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *LevelBaseeTable) RegisterIndexEntry(name string, indexCallback func(*LevelBaseeTable) error, clearCallback func(*LevelBaseeTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *LevelBaseeTable) RegisterPreEntry(callback func(*LevelBaseeTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *LevelBaseeTable) RegisterPostEntry(callback func(*LevelBaseeTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个LevelBasee表读取实例
func NewLevelBaseeTable() *LevelBaseeTable {
	return &LevelBaseeTable{

		indexFuncByName: map[string][]func(*LevelBaseeTable) error{

			"TLevel": {func(tab *LevelBaseeTable) error {

				// TLevel
				for _, def := range tab.TLevel {

					if _, ok := tab.TLevelById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in TLevelById: %v", def.Id))
					}

					tab.TLevelById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*LevelBaseeTable) error{

			"TLevel": {func(tab *LevelBaseeTable) error {

				// TLevel

				tab.TLevelById = make(map[uint32]*TLevelDefine)

				return nil
			}},
		},

		TLevelById: make(map[uint32]*TLevelDefine),
	}
}
