// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: TLoveDialogueBase
type TLoveDialogueBase struct {

	//LoveDialogue
	LoveDialogue []*LoveDialogueDefine
}

// Defined in table: LoveDialogue
type LoveDialogueDefine struct {

	//唯一id
	Id uint32 `json:"id"`

	//宫殿ID
	PalaceId uint32

	//头像
	Headpath string

	//名字
	Name string

	//对话内容
	Content string
}

// 添加init初始实例 "Add By Tse"
var InsTLoveDialogueBaseTable *TLoveDialogueBaseTable

func init() {
	InsTLoveDialogueBaseTable = NewTLoveDialogueBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *TLoveDialogueBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// TLoveDialogueBase 访问接口
type TLoveDialogueBaseTable struct {

	// 表格原始数据
	TLoveDialogueBase

	// 索引函数表
	indexFuncByName map[string][]func(*TLoveDialogueBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*TLoveDialogueBaseTable) error

	// 加载前回调
	preFuncList []func(*TLoveDialogueBaseTable) error

	// 加载后回调
	postFuncList []func(*TLoveDialogueBaseTable) error

	LoveDialogueById map[uint32]*LoveDialogueDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *TLoveDialogueBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab TLoveDialogueBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.TLoveDialogueBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *TLoveDialogueBaseTable) RegisterIndexEntry(name string, indexCallback func(*TLoveDialogueBaseTable) error, clearCallback func(*TLoveDialogueBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *TLoveDialogueBaseTable) RegisterPreEntry(callback func(*TLoveDialogueBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *TLoveDialogueBaseTable) RegisterPostEntry(callback func(*TLoveDialogueBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个TLoveDialogueBase表读取实例
func NewTLoveDialogueBaseTable() *TLoveDialogueBaseTable {
	return &TLoveDialogueBaseTable{

		indexFuncByName: map[string][]func(*TLoveDialogueBaseTable) error{

			"LoveDialogue": {func(tab *TLoveDialogueBaseTable) error {

				// LoveDialogue
				for _, def := range tab.LoveDialogue {

					if _, ok := tab.LoveDialogueById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in LoveDialogueById: %v", def.Id))
					}

					tab.LoveDialogueById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*TLoveDialogueBaseTable) error{

			"LoveDialogue": {func(tab *TLoveDialogueBaseTable) error {

				// LoveDialogue

				tab.LoveDialogueById = make(map[uint32]*LoveDialogueDefine)

				return nil
			}},
		},

		LoveDialogueById: make(map[uint32]*LoveDialogueDefine),
	}
}
