// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: TMaidLevelBase
type TMaidLevelBase struct {

	//TMaidLevel
	TMaidLevel []*TMaidLevelDefine
}

// Defined in table: TMaidLevel
type TMaidLevelDefine struct {

	//id
	Id uint32 `json:"id"`

	//名字
	Name string

	//图片路径
	Path string

	//对话ID
	DialogueID int32

	//所属关卡（配置关卡ID)
	Passlevels int32

	//产生的收益/秒（0个、1万、2亿、3兆、4京、5垓、6秭、7穰、8沟、9涧、10正、11载 、12极）
	Reward []string

	//合成后的ID
	NextID int32

	//商店显示
	UnlockShop []int32

	//角色描述
	RoleDescribe string
}

// 添加init初始实例 "Add By Tse"
var InsTMaidLevelBaseTable *TMaidLevelBaseTable

func init() {
	InsTMaidLevelBaseTable = NewTMaidLevelBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *TMaidLevelBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// TMaidLevelBase 访问接口
type TMaidLevelBaseTable struct {

	// 表格原始数据
	TMaidLevelBase

	// 索引函数表
	indexFuncByName map[string][]func(*TMaidLevelBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*TMaidLevelBaseTable) error

	// 加载前回调
	preFuncList []func(*TMaidLevelBaseTable) error

	// 加载后回调
	postFuncList []func(*TMaidLevelBaseTable) error

	TMaidLevelById map[uint32]*TMaidLevelDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *TMaidLevelBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab TMaidLevelBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.TMaidLevelBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *TMaidLevelBaseTable) RegisterIndexEntry(name string, indexCallback func(*TMaidLevelBaseTable) error, clearCallback func(*TMaidLevelBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *TMaidLevelBaseTable) RegisterPreEntry(callback func(*TMaidLevelBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *TMaidLevelBaseTable) RegisterPostEntry(callback func(*TMaidLevelBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个TMaidLevelBase表读取实例
func NewTMaidLevelBaseTable() *TMaidLevelBaseTable {
	return &TMaidLevelBaseTable{

		indexFuncByName: map[string][]func(*TMaidLevelBaseTable) error{

			"TMaidLevel": {func(tab *TMaidLevelBaseTable) error {

				// TMaidLevel
				for _, def := range tab.TMaidLevel {

					if _, ok := tab.TMaidLevelById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in TMaidLevelById: %v", def.Id))
					}

					tab.TMaidLevelById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*TMaidLevelBaseTable) error{

			"TMaidLevel": {func(tab *TMaidLevelBaseTable) error {

				// TMaidLevel

				tab.TMaidLevelById = make(map[uint32]*TMaidLevelDefine)

				return nil
			}},
		},

		TMaidLevelById: make(map[uint32]*TMaidLevelDefine),
	}
}
