// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: MusicBase
type MusicBase struct {

	//TMusic
	TMusic []*TMusicDefine
}

// Defined in table: TMusic
type TMusicDefine struct {

	//自增id
	Id uint32 `json:"id"`

	//音乐播放位置
	Pos string

	//音乐名称
	Name string
}

// 添加init初始实例 "Add By Tse"
var InsMusicBaseTable *MusicBaseTable

func init() {
	InsMusicBaseTable = NewMusicBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *MusicBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// MusicBase 访问接口
type MusicBaseTable struct {

	// 表格原始数据
	MusicBase

	// 索引函数表
	indexFuncByName map[string][]func(*MusicBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*MusicBaseTable) error

	// 加载前回调
	preFuncList []func(*MusicBaseTable) error

	// 加载后回调
	postFuncList []func(*MusicBaseTable) error

	TMusicById map[uint32]*TMusicDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *MusicBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab MusicBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.MusicBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *MusicBaseTable) RegisterIndexEntry(name string, indexCallback func(*MusicBaseTable) error, clearCallback func(*MusicBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *MusicBaseTable) RegisterPreEntry(callback func(*MusicBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *MusicBaseTable) RegisterPostEntry(callback func(*MusicBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个MusicBase表读取实例
func NewMusicBaseTable() *MusicBaseTable {
	return &MusicBaseTable{

		indexFuncByName: map[string][]func(*MusicBaseTable) error{

			"TMusic": {func(tab *MusicBaseTable) error {

				// TMusic
				for _, def := range tab.TMusic {

					if _, ok := tab.TMusicById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in TMusicById: %v", def.Id))
					}

					tab.TMusicById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*MusicBaseTable) error{

			"TMusic": {func(tab *MusicBaseTable) error {

				// TMusic

				tab.TMusicById = make(map[uint32]*TMusicDefine)

				return nil
			}},
		},

		TMusicById: make(map[uint32]*TMusicDefine),
	}
}
