// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: TPalacePartBase
type TPalacePartBase struct {

	//PalaceParts
	PalaceParts []*PalacePartsDefine
}

// Defined in table: PalaceParts
type PalacePartsDefine struct {

	//id
	Id uint32 `json:"id"`

	//部件id
	PartId uint32

	//等级
	Level uint32

	//升到下一级的消耗
	Cost []string

	//对应的魅力
	Charm uint32

	//家具名字
	PartName string

	//图片路径
	PartPath string
}

// 添加init初始实例 "Add By Tse"
var InsTPalacePartBaseTable *TPalacePartBaseTable

func init() {
	InsTPalacePartBaseTable = NewTPalacePartBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *TPalacePartBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// TPalacePartBase 访问接口
type TPalacePartBaseTable struct {

	// 表格原始数据
	TPalacePartBase

	// 索引函数表
	indexFuncByName map[string][]func(*TPalacePartBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*TPalacePartBaseTable) error

	// 加载前回调
	preFuncList []func(*TPalacePartBaseTable) error

	// 加载后回调
	postFuncList []func(*TPalacePartBaseTable) error

	PalacePartsById map[uint32]*PalacePartsDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *TPalacePartBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab TPalacePartBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.TPalacePartBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *TPalacePartBaseTable) RegisterIndexEntry(name string, indexCallback func(*TPalacePartBaseTable) error, clearCallback func(*TPalacePartBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *TPalacePartBaseTable) RegisterPreEntry(callback func(*TPalacePartBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *TPalacePartBaseTable) RegisterPostEntry(callback func(*TPalacePartBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个TPalacePartBase表读取实例
func NewTPalacePartBaseTable() *TPalacePartBaseTable {
	return &TPalacePartBaseTable{

		indexFuncByName: map[string][]func(*TPalacePartBaseTable) error{

			"PalaceParts": {func(tab *TPalacePartBaseTable) error {

				// PalaceParts
				for _, def := range tab.PalaceParts {

					if _, ok := tab.PalacePartsById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in PalacePartsById: %v", def.Id))
					}

					tab.PalacePartsById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*TPalacePartBaseTable) error{

			"PalaceParts": {func(tab *TPalacePartBaseTable) error {

				// PalaceParts

				tab.PalacePartsById = make(map[uint32]*PalacePartsDefine)

				return nil
			}},
		},

		PalacePartsById: make(map[uint32]*PalacePartsDefine),
	}
}
