// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: TPalacePersonnel
type TPalacePersonnel struct {

	//PalacePersonnel
	PalacePersonnel []*PalacePersonnelDefine
}

// Defined in table: PalacePersonnel
type PalacePersonnelDefine struct {

	//id
	Id uint32 `json:"id"`

	//名字
	Name string

	//图片路径
	Path string

	//图片路径
	WholeBodyPath string

	//角色描述
	RoleDescribe string
}

// 添加init初始实例 "Add By Tse"
var InsTPalacePersonnelTable *TPalacePersonnelTable

func init() {
	InsTPalacePersonnelTable = NewTPalacePersonnelTable()
}

// 添加Reload方法 "Add By Tse"
func (self *TPalacePersonnelTable) Reload() error {
	return self.Load(self.configfile)
}

// TPalacePersonnel 访问接口
type TPalacePersonnelTable struct {

	// 表格原始数据
	TPalacePersonnel

	// 索引函数表
	indexFuncByName map[string][]func(*TPalacePersonnelTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*TPalacePersonnelTable) error

	// 加载前回调
	preFuncList []func(*TPalacePersonnelTable) error

	// 加载后回调
	postFuncList []func(*TPalacePersonnelTable) error

	PalacePersonnelById map[uint32]*PalacePersonnelDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *TPalacePersonnelTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab TPalacePersonnel

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.TPalacePersonnel = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *TPalacePersonnelTable) RegisterIndexEntry(name string, indexCallback func(*TPalacePersonnelTable) error, clearCallback func(*TPalacePersonnelTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *TPalacePersonnelTable) RegisterPreEntry(callback func(*TPalacePersonnelTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *TPalacePersonnelTable) RegisterPostEntry(callback func(*TPalacePersonnelTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个TPalacePersonnel表读取实例
func NewTPalacePersonnelTable() *TPalacePersonnelTable {
	return &TPalacePersonnelTable{

		indexFuncByName: map[string][]func(*TPalacePersonnelTable) error{

			"PalacePersonnel": {func(tab *TPalacePersonnelTable) error {

				// PalacePersonnel
				for _, def := range tab.PalacePersonnel {

					if _, ok := tab.PalacePersonnelById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in PalacePersonnelById: %v", def.Id))
					}

					tab.PalacePersonnelById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*TPalacePersonnelTable) error{

			"PalacePersonnel": {func(tab *TPalacePersonnelTable) error {

				// PalacePersonnel

				tab.PalacePersonnelById = make(map[uint32]*PalacePersonnelDefine)

				return nil
			}},
		},

		PalacePersonnelById: make(map[uint32]*PalacePersonnelDefine),
	}
}
