// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: TRewardBase
type TRewardBase struct {

	//Reward
	Reward []*RewardDefine
}

// Defined in table: Reward
type RewardDefine struct {

	//id
	Id uint32 `json:"id"`

	//掉落id
	DropId uint32

	//概率类型 1 万分比 2 权重
	PropType uint32

	//概率或权重
	Prop uint32

	//奖励类型(1 金币 2 体力 3 物品 4 亲密度 5 小游戏币 6 另一个掉落 7 小游戏)
	RewardType uint32

	//奖励id
	RewardId uint32

	//奖励数量
	RewardValue uint32
}

// 添加init初始实例 "Add By Tse"
var InsTRewardBaseTable *TRewardBaseTable

func init() {
	InsTRewardBaseTable = NewTRewardBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *TRewardBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// TRewardBase 访问接口
type TRewardBaseTable struct {

	// 表格原始数据
	TRewardBase

	// 索引函数表
	indexFuncByName map[string][]func(*TRewardBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*TRewardBaseTable) error

	// 加载前回调
	preFuncList []func(*TRewardBaseTable) error

	// 加载后回调
	postFuncList []func(*TRewardBaseTable) error

	RewardById map[uint32]*RewardDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *TRewardBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab TRewardBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.TRewardBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *TRewardBaseTable) RegisterIndexEntry(name string, indexCallback func(*TRewardBaseTable) error, clearCallback func(*TRewardBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *TRewardBaseTable) RegisterPreEntry(callback func(*TRewardBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *TRewardBaseTable) RegisterPostEntry(callback func(*TRewardBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个TRewardBase表读取实例
func NewTRewardBaseTable() *TRewardBaseTable {
	return &TRewardBaseTable{

		indexFuncByName: map[string][]func(*TRewardBaseTable) error{

			"Reward": {func(tab *TRewardBaseTable) error {

				// Reward
				for _, def := range tab.Reward {

					if _, ok := tab.RewardById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in RewardById: %v", def.Id))
					}

					tab.RewardById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*TRewardBaseTable) error{

			"Reward": {func(tab *TRewardBaseTable) error {

				// Reward

				tab.RewardById = make(map[uint32]*RewardDefine)

				return nil
			}},
		},

		RewardById: make(map[uint32]*RewardDefine),
	}
}
