// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: TShareBase
type TShareBase struct {

	//Share
	Share []*ShareDefine
}

// Defined in table: Share
type ShareDefine struct {

	//唯一id
	Id uint32 `json:"id"`

	//1 合并新形象 2 新关卡 3 新章节 4 招募分享 5 体力分享 6小游戏次数分享 7 回忆录分享  8 随机约会结果分享 9 翻牌结果分享
	ShareType uint32

	//id
	ShareId uint32

	//0 没有时间限制 随意分享 1 每天 2 和上一次不一样就行
	FreshType uint32

	//奖励id /倍数
	Reward uint32

	//在时间范围内的次数限制
	Times uint32

	//分享标题
	Title string

	//分享图片路径
	Image string
}

// 添加init初始实例 "Add By Tse"
var InsTShareBaseTable *TShareBaseTable

func init() {
	InsTShareBaseTable = NewTShareBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *TShareBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// TShareBase 访问接口
type TShareBaseTable struct {

	// 表格原始数据
	TShareBase

	// 索引函数表
	indexFuncByName map[string][]func(*TShareBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*TShareBaseTable) error

	// 加载前回调
	preFuncList []func(*TShareBaseTable) error

	// 加载后回调
	postFuncList []func(*TShareBaseTable) error

	ShareById map[uint32]*ShareDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *TShareBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab TShareBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.TShareBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *TShareBaseTable) RegisterIndexEntry(name string, indexCallback func(*TShareBaseTable) error, clearCallback func(*TShareBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *TShareBaseTable) RegisterPreEntry(callback func(*TShareBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *TShareBaseTable) RegisterPostEntry(callback func(*TShareBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个TShareBase表读取实例
func NewTShareBaseTable() *TShareBaseTable {
	return &TShareBaseTable{

		indexFuncByName: map[string][]func(*TShareBaseTable) error{

			"Share": {func(tab *TShareBaseTable) error {

				// Share
				for _, def := range tab.Share {

					if _, ok := tab.ShareById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in ShareById: %v", def.Id))
					}

					tab.ShareById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*TShareBaseTable) error{

			"Share": {func(tab *TShareBaseTable) error {

				// Share

				tab.ShareById = make(map[uint32]*ShareDefine)

				return nil
			}},
		},

		ShareById: make(map[uint32]*ShareDefine),
	}
}
