// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: ShopBase
type ShopBase struct {

	//TShop
	TShop []*TShopDefine
}

// Defined in table: TShop
type TShopDefine struct {

	//商城ID
	Id uint32 `json:"id"`

	//商品id
	Itemid int32

	//道具名
	Name string

	//商品类型
	Type int32

	//数量
	Num int32

	//人民币价值
	Rmb int32

	//价格
	Price int32

	//运费
	Send int32
}

// 添加init初始实例 "Add By Tse"
var InsShopBaseTable *ShopBaseTable

func init() {
	InsShopBaseTable = NewShopBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *ShopBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// ShopBase 访问接口
type ShopBaseTable struct {

	// 表格原始数据
	ShopBase

	// 索引函数表
	indexFuncByName map[string][]func(*ShopBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*ShopBaseTable) error

	// 加载前回调
	preFuncList []func(*ShopBaseTable) error

	// 加载后回调
	postFuncList []func(*ShopBaseTable) error

	TShopById map[uint32]*TShopDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *ShopBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab ShopBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.ShopBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *ShopBaseTable) RegisterIndexEntry(name string, indexCallback func(*ShopBaseTable) error, clearCallback func(*ShopBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *ShopBaseTable) RegisterPreEntry(callback func(*ShopBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *ShopBaseTable) RegisterPostEntry(callback func(*ShopBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个ShopBase表读取实例
func NewShopBaseTable() *ShopBaseTable {
	return &ShopBaseTable{

		indexFuncByName: map[string][]func(*ShopBaseTable) error{

			"TShop": {func(tab *ShopBaseTable) error {

				// TShop
				for _, def := range tab.TShop {

					if _, ok := tab.TShopById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in TShopById: %v", def.Id))
					}

					tab.TShopById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*ShopBaseTable) error{

			"TShop": {func(tab *ShopBaseTable) error {

				// TShop

				tab.TShopById = make(map[uint32]*TShopDefine)

				return nil
			}},
		},

		TShopById: make(map[uint32]*TShopDefine),
	}
}
