// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: SignBase
type SignBase struct {

	//TSign
	TSign []*TSignDefine
}

// Defined in table: TSign
type TSignDefine struct {

	//签到ID
	Id uint32 `json:"id"`

	//花费ID
	CostId int32

	//数量
	Num int32
}

// 添加init初始实例 "Add By Tse"
var InsSignBaseTable *SignBaseTable

func init() {
	InsSignBaseTable = NewSignBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *SignBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// SignBase 访问接口
type SignBaseTable struct {

	// 表格原始数据
	SignBase

	// 索引函数表
	indexFuncByName map[string][]func(*SignBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*SignBaseTable) error

	// 加载前回调
	preFuncList []func(*SignBaseTable) error

	// 加载后回调
	postFuncList []func(*SignBaseTable) error

	TSignById map[uint32]*TSignDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *SignBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab SignBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.SignBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *SignBaseTable) RegisterIndexEntry(name string, indexCallback func(*SignBaseTable) error, clearCallback func(*SignBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *SignBaseTable) RegisterPreEntry(callback func(*SignBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *SignBaseTable) RegisterPostEntry(callback func(*SignBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个SignBase表读取实例
func NewSignBaseTable() *SignBaseTable {
	return &SignBaseTable{

		indexFuncByName: map[string][]func(*SignBaseTable) error{

			"TSign": {func(tab *SignBaseTable) error {

				// TSign
				for _, def := range tab.TSign {

					if _, ok := tab.TSignById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in TSignById: %v", def.Id))
					}

					tab.TSignById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*SignBaseTable) error{

			"TSign": {func(tab *SignBaseTable) error {

				// TSign

				tab.TSignById = make(map[uint32]*TSignDefine)

				return nil
			}},
		},

		TSignById: make(map[uint32]*TSignDefine),
	}
}
