// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: TaskBase
type TaskBase struct {

	//TTask
	TTask []*TTaskDefine
}

// Defined in table: TTask
type TTaskDefine struct {

	//id
	Id uint32 `json:"id"`

	//描述
	Desc string

	//计数
	Count int32

	//奖励
	Reward string
}

// 添加init初始实例 "Add By Tse"
var InsTaskBaseTable *TaskBaseTable

func init() {
	InsTaskBaseTable = NewTaskBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *TaskBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// TaskBase 访问接口
type TaskBaseTable struct {

	// 表格原始数据
	TaskBase

	// 索引函数表
	indexFuncByName map[string][]func(*TaskBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*TaskBaseTable) error

	// 加载前回调
	preFuncList []func(*TaskBaseTable) error

	// 加载后回调
	postFuncList []func(*TaskBaseTable) error

	TTaskById map[uint32]*TTaskDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *TaskBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab TaskBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.TaskBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *TaskBaseTable) RegisterIndexEntry(name string, indexCallback func(*TaskBaseTable) error, clearCallback func(*TaskBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *TaskBaseTable) RegisterPreEntry(callback func(*TaskBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *TaskBaseTable) RegisterPostEntry(callback func(*TaskBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个TaskBase表读取实例
func NewTaskBaseTable() *TaskBaseTable {
	return &TaskBaseTable{

		indexFuncByName: map[string][]func(*TaskBaseTable) error{

			"TTask": {func(tab *TaskBaseTable) error {

				// TTask
				for _, def := range tab.TTask {

					if _, ok := tab.TTaskById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in TTaskById: %v", def.Id))
					}

					tab.TTaskById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*TaskBaseTable) error{

			"TTask": {func(tab *TaskBaseTable) error {

				// TTask

				tab.TTaskById = make(map[uint32]*TTaskDefine)

				return nil
			}},
		},

		TTaskById: make(map[uint32]*TTaskDefine),
	}
}
