// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10
// DO NOT EDIT!!
package table

import (
	"fmt"
	"encoding/json"
	"io/ioutil"
)

// Defined in table: TTurnBrandBase
type TTurnBrandBase struct {

	//TurnBrand
	TurnBrand []*TurnBrandDefine
}

// Defined in table: TurnBrand
type TurnBrandDefine struct {

	//id
	Id uint32 `json:"id"`

	//名字
	Name string

	//图片路径
	Head string

	//掉落id
	Reward uint32

	//对话
	Dialogue uint32

	//权重
	Weight uint32
}

// 添加init初始实例 "Add By Tse"
var InsTTurnBrandBaseTable *TTurnBrandBaseTable

func init() {
	InsTTurnBrandBaseTable = NewTTurnBrandBaseTable()
}

// 添加Reload方法 "Add By Tse"
func (self *TTurnBrandBaseTable) Reload() error {
	return self.Load(self.configfile)
}

// TTurnBrandBase 访问接口
type TTurnBrandBaseTable struct {

	// 表格原始数据
	TTurnBrandBase

	// 索引函数表
	indexFuncByName map[string][]func(*TTurnBrandBaseTable) error

	// 清空函数表
	clearFuncByName map[string][]func(*TTurnBrandBaseTable) error

	// 加载前回调
	preFuncList []func(*TTurnBrandBaseTable) error

	// 加载后回调
	postFuncList []func(*TTurnBrandBaseTable) error

	TurnBrandById map[uint32]*TurnBrandDefine

	// 配置文件
	configfile string
}

// 从json文件加载
func (self *TTurnBrandBaseTable) Load(filename string) error {
	self.configfile = filename
	data, err := ioutil.ReadFile(filename)

	if err != nil {
		return err
	}

	var newTab TTurnBrandBase

	// 读取
	err = json.Unmarshal(data, &newTab)
	if err != nil {
		return err
	}

	// 所有加载前的回调
	for _, v := range self.preFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	// 清除前通知
	for _, list := range self.clearFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 复制数据
	self.TTurnBrandBase = newTab

	// 生成索引
	for _, list := range self.indexFuncByName {
		for _, v := range list {
			if err = v(self); err != nil {
				return err
			}
		}
	}

	// 所有完成时的回调
	for _, v := range self.postFuncList {
		if err = v(self); err != nil {
			return err
		}
	}

	return nil
}

// 注册外部索引入口, 索引回调, 清空回调
func (self *TTurnBrandBaseTable) RegisterIndexEntry(name string, indexCallback func(*TTurnBrandBaseTable) error, clearCallback func(*TTurnBrandBaseTable) error) {

	indexList, _ := self.indexFuncByName[name]
	clearList, _ := self.clearFuncByName[name]

	if indexCallback != nil {
		indexList = append(indexList, indexCallback)
	}

	if clearCallback != nil {
		clearList = append(clearList, clearCallback)
	}

	self.indexFuncByName[name] = indexList
	self.clearFuncByName[name] = clearList
}

// 注册加载前回调
func (self *TTurnBrandBaseTable) RegisterPreEntry(callback func(*TTurnBrandBaseTable) error) {

	self.preFuncList = append(self.preFuncList, callback)
}

// 注册所有完成时回调
func (self *TTurnBrandBaseTable) RegisterPostEntry(callback func(*TTurnBrandBaseTable) error) {

	self.postFuncList = append(self.postFuncList, callback)
}

// 创建一个TTurnBrandBase表读取实例
func NewTTurnBrandBaseTable() *TTurnBrandBaseTable {
	return &TTurnBrandBaseTable{

		indexFuncByName: map[string][]func(*TTurnBrandBaseTable) error{

			"TurnBrand": {func(tab *TTurnBrandBaseTable) error {

				// TurnBrand
				for _, def := range tab.TurnBrand {

					if _, ok := tab.TurnBrandById[def.Id]; ok {
						panic(fmt.Sprintf("duplicate index in TurnBrandById: %v", def.Id))
					}

					tab.TurnBrandById[def.Id] = def

				}

				return nil
			}},
		},

		clearFuncByName: map[string][]func(*TTurnBrandBaseTable) error{

			"TurnBrand": {func(tab *TTurnBrandBaseTable) error {

				// TurnBrand

				tab.TurnBrandById = make(map[uint32]*TurnBrandDefine)

				return nil
			}},
		},

		TurnBrandById: make(map[uint32]*TurnBrandDefine),
	}
}
