// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var DropBox : table.IDropBoxDefine[] = [
		{ Id : 1, BoxPath : "Image/GameScene/Event/1001", Type : 5, RewardId : 1, Value : 1, Interval : 10, Level : 1 	}
	]


// Id
export var DropBoxById : game.Dictionary<table.IDropBoxDefine> = {}
function readDropBoxById(){
  for(let rec of DropBox) {
    DropBoxById[rec.Id] = rec; 
  }
}
readDropBoxById();
}

