// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var DateEvent : table.IDateEventDefine[] = [
		{ Id : 1, Datetype : 1, DateId : 101, Datepath : "Image/GameScene/Palace/101", DateName : "清晨" 	},
		{ Id : 2, Datetype : 1, DateId : 102, Datepath : "Image/GameScene/Palace/102", DateName : "上午" 	},
		{ Id : 3, Datetype : 1, DateId : 103, Datepath : "Image/GameScene/Palace/103", DateName : "中午" 	},
		{ Id : 4, Datetype : 1, DateId : 104, Datepath : "Image/GameScene/Palace/104", DateName : "下午" 	},
		{ Id : 5, Datetype : 1, DateId : 105, Datepath : "Image/GameScene/Palace/105", DateName : "晚上" 	},
		{ Id : 6, Datetype : 2, DateId : 201, Datepath : "Image/GameScene/Palace/201", DateName : "御花园" 	},
		{ Id : 7, Datetype : 2, DateId : 202, Datepath : "Image/GameScene/Palace/202", DateName : "亭子里" 	},
		{ Id : 8, Datetype : 2, DateId : 203, Datepath : "Image/GameScene/Palace/203", DateName : "延晖阁" 	},
		{ Id : 9, Datetype : 2, DateId : 204, Datepath : "Image/GameScene/Palace/204", DateName : "狩猎场" 	},
		{ Id : 10, Datetype : 2, DateId : 205, Datepath : "Image/GameScene/Palace/205", DateName : "房间内" 	},
		{ Id : 11, Datetype : 3, DateId : 301, Datepath : "Image/GameScene/Palace/301", DateName : "赏花" 	},
		{ Id : 12, Datetype : 3, DateId : 302, Datepath : "Image/GameScene/Palace/302", DateName : "赏月" 	},
		{ Id : 13, Datetype : 3, DateId : 303, Datepath : "Image/GameScene/Palace/303", DateName : "赏画" 	},
		{ Id : 14, Datetype : 3, DateId : 304, Datepath : "Image/GameScene/Palace/304", DateName : "骑马" 	},
		{ Id : 15, Datetype : 3, DateId : 305, Datepath : "Image/GameScene/Palace/305", DateName : "弹琴" 	}
	]


// Id
export var DateEventById : game.Dictionary<table.IDateEventDefine> = {}
function readDateEventById(){
  for(let rec of DateEvent) {
    DateEventById[rec.Id] = rec; 
  }
}
readDateEventById();
}

