// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TDialogue : table.ITDialogueDefine[] = [
		{ Id : 1, Index : 1, HeadSprite : [ "Image/Head/2" ], HeadLocation : [ 1 ], Name : "皇上", NameLocation : 1, Content : "这秀女，今天风这么大，站着挺费劲儿吧。" 	},
		{ Id : 2, Index : 1, HeadSprite : [ "Image/Head/2", "Image/Head/3" ], HeadLocation : [ 1, 2 ], Name : "李玉", NameLocation : 2, Content : "皇上说你太瘦，赐花。" 	},
		{ Id : 3, Index : 2, HeadSprite : [ "Image/Head/2" ], HeadLocation : [ 1 ], Name : "皇上", NameLocation : 1, Content : "你这是一天吃五顿饭。" 	},
		{ Id : 4, Index : 2, HeadSprite : [ "Image/Head/2", "Image/Head/3" ], HeadLocation : [ 1, 2 ], Name : "李玉", NameLocation : 2, Content : "皇上说你太胖，赐花。" 	},
		{ Id : 5, Index : 3, HeadSprite : [ "Image/Head/2" ], HeadLocation : [ 1 ], Name : "皇上", NameLocation : 1, Content : "你是每天顶着酱油晒太阳吗？" 	},
		{ Id : 6, Index : 3, HeadSprite : [ "Image/Head/2", "Image/Head/3" ], HeadLocation : [ 1, 2 ], Name : "李玉", NameLocation : 2, Content : "皇上说你太黑了，赐花。" 	},
		{ Id : 7, Index : 4, HeadSprite : [ "Image/Head/3" ], HeadLocation : [ 1 ], Name : "李玉", NameLocation : 1, Content : "光禄寺少卿陆士隆之女陆晚晚，年十六！" 	},
		{ Id : 8, Index : 5, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 1 ], Name : "纳兰淳雪", NameLocation : 1, Content : "皇上，女子一耳带三钳，穿花盆鞋，乃是老祖宗留下的规矩，若是一朝抛弃，效法汉女一耳一坠，就是忘了祖宗。" 	},
		{ Id : 9, Index : 5, HeadSprite : [ "Image/Head/4", "Image/Head/2" ], HeadLocation : [ 1, 2 ], Name : "皇上", NameLocation : 2, Content : "嗯，说的不错。" 	},
		{ Id : 10, Index : 5, HeadSprite : [ "Image/Head/4", "Image/Head/3" ], HeadLocation : [ 1, 2 ], Name : "李玉", NameLocation : 2, Content : "留牌子。" 	},
		{ Id : 11, Index : 6, HeadSprite : [ "Image/Head/2" ], HeadLocation : [ 1 ], Name : "皇上", NameLocation : 1, Content : "你这脚上是怎么回事？" 	},
		{ Id : 12, Index : 6, HeadSprite : [ "Image/Head/2", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "乌雅青黛", NameLocation : 2, Content : "回皇上，臣女这叫步步生莲。" 	},
		{ Id : 13, Index : 6, HeadSprite : [ "Image/Head/2", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "皇上", NameLocation : 1, Content : "来人，叉出去。" 	},
		{ Id : 14, Index : 6, HeadSprite : [ "Image/Head/2", "Image/Head/1" ], HeadLocation : [ 1, 2 ], Name : "富察皇后", NameLocation : 2, Content : "皇上，秀女想要拔个头筹，也没有什么不对，您若是不喜欢，赐花就是了，这样驱逐出宫，她以后有何颜面见人。" 	},
		{ Id : 15, Index : 6, HeadSprite : [ "Image/Head/2", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "乌雅青黛", NameLocation : 2, Content : "皇上，皇上，臣女只是仿照步步生莲，想要博个头彩，皇上宽恕！" 	},
		{ Id : 16, Index : 6, HeadSprite : [ "Image/Head/2", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "皇上", NameLocation : 1, Content : "朕早已明令，禁止汉军旗秀女缠足，如今乌雅氏也学此等奢靡颓废风气，这样的女子进了宫，一定会惹出是非，驱逐出宫，以儆效尤！" 	},
		{ Id : 17, Index : 6, HeadSprite : [ "Image/Head/2", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "乌雅青黛", NameLocation : 2, Content : "不要啊！皇上！臣女知错了！对了，是那贱婢害了臣女！往鞋底涂抹香粉的主意不是我……呜！" 	},
		{ Id : 18, Index : 7, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 2 ], Name : "娴妃", NameLocation : 2, Content : "臣妾准备了一双玉如意，恭祝娘娘福泽绵长 万事如意。" 	},
		{ Id : 19, Index : 7, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "富察皇后", NameLocation : 1, Content : "(微笑点头)" 	},
		{ Id : 20, Index : 8, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 2 ], Name : "纯妃", NameLocation : 2, Content : "皇后娘娘，臣妾准备一块暖玉，非常适合娘娘体质。" 	},
		{ Id : 21, Index : 8, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "富察皇后", NameLocation : 1, Content : "纯妃有心了，本宫很喜欢。" 	},
		{ Id : 22, Index : 9, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 2 ], Name : "舒贵人", NameLocation : 2, Content : "皇后娘娘，臣妾托人打造了一个宝石盆景。您看喜不喜欢。" 	},
		{ Id : 23, Index : 9, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "富察皇后", NameLocation : 1, Content : "真是漂亮。" 	},
		{ Id : 24, Index : 10, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 2 ], Name : "高贵妃", NameLocation : 2, Content : "皇后娘娘，臣妾特意命人为您打造了一尊送子观音。您可喜欢呀。" 	},
		{ Id : 25, Index : 10, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "富察皇后", NameLocation : 1, Content : "(强压怒火)高贵妃一番美意，这份厚礼，本宫收下了。" 	},
		{ Id : 26, Index : 11, HeadSprite : [ "Image/Head/3" ], HeadLocation : [ 2 ], Name : "李玉", NameLocation : 2, Content : "皇上有赏。恭祝皇后娘娘福寿康宁。这是皇上特意为娘娘准备的一件礼物——报时妆奁。" 	},
		{ Id : 27, Index : 11, HeadSprite : [ "Image/Head/1", "Image/Head/3" ], HeadLocation : [ 1, 2 ], Name : "皇后", NameLocation : 1, Content : "臣妾谢皇上厚恩。" 	},
		{ Id : 28, Index : 12, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 2 ], Name : "魏璎珞", NameLocation : 2, Content : "恭贺皇后娘娘，芳龄永驻，福寿绵长。" 	},
		{ Id : 29, Index : 12, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "富察皇后", NameLocation : 1, Content : "这既不是金线也不是银线。这到底是用什么织的？" 	},
		{ Id : 30, Index : 12, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 2 ], Name : "魏璎珞", NameLocation : 2, Content : "回禀皇后娘娘，听闻皇后娘娘素来节俭。今年特意用了鹿尾绒毛搓成的丝线。" 	},
		{ Id : 31, Index : 12, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "皇后", NameLocation : 1, Content : "来人啊，赏！" 	},
		{ Id : 32, Index : 13, HeadSprite : [ "Image/Head/5" ], HeadLocation : [ 1 ], Name : "侍卫", NameLocation : 1, Content : "我会守护你的一生。" 	},
		{ Id : 33, Index : 14, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 1 ], Name : "皇后", NameLocation : 1, Content : "我就是你的白月光。" 	},
		{ Id : 34, Index : 15, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 2 ], Name : "旁白", NameLocation : 2, Content : "年久失修的义庄内。" 	},
		{ Id : 35, Index : 15, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 1 ], Name : "魏璎珞", NameLocation : 1, Content : "姐姐，你我怎么会在这种地方见面。" 	},
		{ Id : 36, Index : 15, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 1 ], Name : "魏璎珞", NameLocation : 1, Content : "他们都说你没资格葬入祖坟，我不信他们的话，姐，我要你亲口告诉我真相……" 	},
		{ Id : 37, Index : 16, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 1 ], Name : "魏清泰", NameLocation : 1, Content : "璎珞，住手。" 	},
		{ Id : 38, Index : 16, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "旁白", NameLocation : 2, Content : "璎珞轰的砍了下去。" 	},
		{ Id : 39, Index : 16, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 1 ], Name : "魏清泰", NameLocation : 1, Content : "你，你在干什么啊？这可是你姐姐的棺材啊……" 	},
		{ Id : 40, Index : 17, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 1 ], Name : "魏璎珞", NameLocation : 1, Content : "有人说姐姐是病死的，也有的说她是在宫里做了丑事，没脸见人才自尽身亡的。" 	},
		{ Id : 41, Index : 17, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 1 ], Name : "魏璎珞", NameLocation : 1, Content : "看看她脖子上的手印，告诉我，一个人，该怎么把自己给掐死？" 	},
		{ Id : 42, Index : 18, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 2 ], Name : "魏清泰", NameLocation : 2, Content : "不要再追究了，快跟我回家。" 	},
		{ Id : 43, Index : 18, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "魏璎珞", NameLocation : 1, Content : "不……我要进宫。查明真凶，为我姐姐报仇。" 	},
		{ Id : 44, Index : 19, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 1 ], Name : "旁白", NameLocation : 1, Content : "吉祥看着远处预备殿选的秀女。" 	},
		{ Id : 45, Index : 19, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "吉祥", NameLocation : 2, Content : "我要是能穿上这么漂亮的衣服就好了。" 	},
		{ Id : 46, Index : 20, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 1 ], Name : "锦绣", NameLocation : 1, Content : "少做白日梦了！" 	},
		{ Id : 47, Index : 20, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "旁白", NameLocation : 2, Content : "被锦绣一撞吉祥拎的水桶弄脏了乌雅秀女的裙子。" 	},
		{ Id : 48, Index : 20, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "吉祥", NameLocation : 1, Content : "对不起，对不起，我现在就帮你擦干净……" 	},
		{ Id : 49, Index : 21, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 1 ], Name : "乌雅青黛", NameLocation : 1, Content : "混账奴才！你现在弄脏了，要我穿什么去见皇上！" 	},
		{ Id : 50, Index : 21, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "吉祥", NameLocation : 2, Content : "奴才给您擦，奴才马上就给您擦干净……" 	},
		{ Id : 51, Index : 21, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "乌雅青黛", NameLocation : 1, Content : "既然弄脏了我的衣裳，就用你这只手来赔吧!(言罢，一只脚便重重碾在吉祥的手背上)" 	},
		{ Id : 52, Index : 21, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "吉祥", NameLocation : 2, Content : "好疼啊，饶命啊，救救我!" 	},
		{ Id : 53, Index : 22, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 1 ], Name : "魏璎珞", NameLocation : 1, Content : "乌雅小主。请高抬贵脚。" 	},
		{ Id : 54, Index : 22, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "乌雅青黛", NameLocation : 2, Content : "你一个小小宫女，也妄想请我容情？" 	},
		{ Id : 55, Index : 22, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "魏璎珞", NameLocation : 1, Content : "小主匠心独运，特意将鞋底雕刻成莲花形状，可惜还少了一样东西，奴才斗胆，愿为小主分忧。" 	},
		{ Id : 56, Index : 23, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 2 ], Name : "乌雅青黛", NameLocation : 2, Content : "如何分忧？" 	},
		{ Id : 57, Index : 23, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "魏璎珞", NameLocation : 1, Content : "请乌雅小主抬足。" 	},
		{ Id : 58, Index : 23, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "旁白", NameLocation : 2, Content : "(魏璎珞双手捧着乌雅青黛的绣鞋，然后以香囊沾粉，均匀的将香粉涂抹在乌雅青黛的鞋底，神情专注)" 	},
		{ Id : 59, Index : 24, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 1 ], Name : "魏璎珞", NameLocation : 1, Content : "今日璎珞雕虫小技，用玫瑰花粉嵌入鞋底，祝愿小主心愿得偿、步步高升！" 	},
		{ Id : 60, Index : 24, HeadSprite : [ "Image/Head/1", "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "乌雅青黛", NameLocation : 2, Content : "就冲你这哈巴狗的样，我饶她一命！" 	},
		{ Id : 61, Index : 25, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 1 ], Name : "魏璎珞", NameLocation : 1, Content : "珍珠你好，我是新来的魏璎珞" 	},
		{ Id : 62, Index : 26, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 1 ], Name : "魏璎珞", NameLocation : 1, Content : "玛瑙，我来帮你一起打扫吧" 	},
		{ Id : 63, Index : 27, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 1 ], Name : "魏璎珞", NameLocation : 1, Content : "翡翠，有需要我帮忙的吗。" 	},
		{ Id : 64, Index : 28, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 1 ], Name : "魏璎珞", NameLocation : 1, Content : "琥珀，还有哪里需要我做的。" 	},
		{ Id : 65, Index : 29, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 2 ], Name : "明玉", NameLocation : 2, Content : "真不知道皇后娘娘看中你什么，一个小小绣女也能来长春宫。" 	},
		{ Id : 66, Index : 29, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "魏璎珞", NameLocation : 1, Content : "明玉姐姐说的是。" 	},
		{ Id : 67, Index : 30, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 1 ], Name : "魏璎珞", NameLocation : 1, Content : "我终于到了长春宫，为姐姐报仇，查找真正凶手。" 	},
		{ Id : 68, Index : 31, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 2 ], Name : "尔晴", NameLocation : 2, Content : "好了璎珞，这收拾的挺干净的，回去休息吧。" 	},
		{ Id : 69, Index : 31, HeadSprite : [ "Image/Head/4" ], HeadLocation : [ 1, 2 ], Name : "魏璎珞", NameLocation : 1, Content : "谢谢尔晴姐姐。" 	},
		{ Id : 70, Index : 32, HeadSprite : [ "Image/Head/1" ], HeadLocation : [ 1 ], Name : "富察皇后", NameLocation : 1, Content : "我看这丫头挺机灵的，全当来给我逗个闷儿。" 	}
	]


// Id
export var TDialogueById : game.Dictionary<table.ITDialogueDefine> = {}
function readTDialogueById(){
  for(let rec of TDialogue) {
    TDialogueById[rec.Id] = rec; 
  }
}
readTDialogueById();
}

