// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Event : table.IEventDefine[] = [
		{ Id : 1, EventName : "璎珞保护茉莉花", EventPath : "Image/GameScene/Event/1001", DefaultBarrage : [ "1_哈哈哈哈", "2_嘻嘻嘻嘻" ] 	},
		{ Id : 2, EventName : "茉莉花遭雨淋", EventPath : "Image/GameScene/Event/1002", DefaultBarrage : [ "1_哈哈哈哈", "2_嘻嘻嘻嘻" ] 	},
		{ Id : 3, EventName : "宫女感冒", EventPath : "Image/GameScene/Event/1003", DefaultBarrage : [ "1_哈哈哈哈", "2_嘻嘻嘻嘻" ] 	}
	]


// Id
export var EventById : game.Dictionary<table.IEventDefine> = {}
function readEventById(){
  for(let rec of Event) {
    EventById[rec.Id] = rec; 
  }
}
readEventById();
}

