// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Head : table.IHeadDefine[] = [
		{ Id : 1, HeadPath : "1001", Name : "璎珞保护茉莉花" 	}
	]


// Id
export var HeadById : game.Dictionary<table.IHeadDefine> = {}
function readHeadById(){
  for(let rec of Head) {
    HeadById[rec.Id] = rec; 
  }
}
readHeadById();
}

