// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TMaidShop : table.ITMaidShopDefine[] = [
		{ Id : 1, Price : 10 	},
		{ Id : 2, Price : 15 	},
		{ Id : 3, Price : 23 	},
		{ Id : 4, Price : 34 	},
		{ Id : 5, Price : 51 	},
		{ Id : 6, Price : 76 	},
		{ Id : 7, Price : 114 	},
		{ Id : 8, Price : 171 	},
		{ Id : 9, Price : 257 	},
		{ Id : 10, Price : 385 	},
		{ Id : 11, Price : 577 	},
		{ Id : 12, Price : 865 	},
		{ Id : 13, Price : 1298 	},
		{ Id : 14, Price : 1947 	},
		{ Id : 15, Price : 2920 	},
		{ Id : 16, Price : 4379 	},
		{ Id : 17, Price : 6569 	},
		{ Id : 18, Price : 9853 	},
		{ Id : 19, Price : 14779 	},
		{ Id : 20, Price : 22169 	},
		{ Id : 21, Price : 33253 	},
		{ Id : 22, Price : 49879 	},
		{ Id : 23, Price : 74819 	},
		{ Id : 24, Price : 112228 	},
		{ Id : 25, Price : 168342 	},
		{ Id : 26, Price : 252512 	},
		{ Id : 27, Price : 378768 	},
		{ Id : 28, Price : 568152 	},
		{ Id : 29, Price : 852227 	},
		{ Id : 30, Price : 1278341 	},
		{ Id : 31, Price : 1917511 	},
		{ Id : 32, Price : 2876266 	},
		{ Id : 33, Price : 4314399 	},
		{ Id : 34, Price : 6471599 	},
		{ Id : 35, Price : 9707398 	},
		{ Id : 36, Price : 14561097 	},
		{ Id : 37, Price : 21841645 	},
		{ Id : 38, Price : 32762467 	}
	]


// Id
export var TMaidShopById : game.Dictionary<table.ITMaidShopDefine> = {}
function readTMaidShopById(){
  for(let rec of TMaidShop) {
    TMaidShopById[rec.Id] = rec; 
  }
}
readTMaidShopById();
}

