// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TMaidLevel : table.ITMaidLevelDefine[] = [
		{ Id : 1, Name : "瘦秀女", Path : "Image/GameScene/Maid/maid_1", Passlevels : 1, Reward : [ "0_1" ], NextID : 2, ShopShow : [ 1 ], DialogueID : 0, RoleDescribe : "" 	},
		{ Id : 2, Name : "胖秀女", Path : "Image/GameScene/Maid/maid_2", Passlevels : 1, Reward : [ "0_3" ], NextID : 3, ShopShow : [ 1 ], DialogueID : 0, RoleDescribe : "" 	},
		{ Id : 3, Name : "黑秀女", Path : "Image/GameScene/Maid/maid_3", Passlevels : 2, Reward : [ "0_5" ], NextID : 4, ShopShow : [ 1 ], DialogueID : 0, RoleDescribe : "" 	},
		{ Id : 4, Name : "陆晚晚", Path : "Image/GameScene/Maid/maid_4", Passlevels : 2, Reward : [ "0_7" ], NextID : 5, ShopShow : [ 1 ], DialogueID : 4, RoleDescribe : "" 	},
		{ Id : 5, Name : "纳兰淳雪", Path : "Image/GameScene/Maid/maid_5", Passlevels : 2, Reward : [ "0_9" ], NextID : 6, ShopShow : [ 1 ], DialogueID : 5, RoleDescribe : "" 	},
		{ Id : 6, Name : "乌雅青黛", Path : "Image/GameScene/Maid/maid_6", Passlevels : 2, Reward : [ "0_11" ], NextID : 7, ShopShow : [ 1, 2 ], DialogueID : 6, RoleDescribe : "" 	},
		{ Id : 7, Name : "牡丹图", Path : "Image/GameScene/Maid/maid_20", Passlevels : 3, Reward : [ "0_13" ], NextID : 8, ShopShow : [ 1, 2, 3 ], DialogueID : 0, RoleDescribe : "" 	},
		{ Id : 8, Name : "金鸡图", Path : "Image/GameScene/Maid/maid_21", Passlevels : 3, Reward : [ "0_15" ], NextID : 9, ShopShow : [ 1, 2, 3, 4 ], DialogueID : 34, RoleDescribe : "" 	},
		{ Id : 9, Name : "吉祥哭", Path : "Image/GameScene/Maid/maid_22", Passlevels : 3, Reward : [ "0_17" ], NextID : 10, ShopShow : [ 1, 2, 3, 4, 5 ], DialogueID : 35, RoleDescribe : "" 	},
		{ Id : 10, Name : "璎珞翘舌", Path : "Image/GameScene/Maid/maid_23", Passlevels : 3, Reward : [ "0_19" ], NextID : 11, ShopShow : [ 1, 2, 3, 4, 5, 6 ], DialogueID : 36, RoleDescribe : "" 	},
		{ Id : 11, Name : "张嬷嬷", Path : "Image/GameScene/Maid/maid_24", Passlevels : 3, Reward : [ "0_21" ], NextID : 12, ShopShow : [ 1, 2, 3, 4, 5, 6, 7 ], DialogueID : 37, RoleDescribe : "" 	},
		{ Id : 12, Name : "吴总管", Path : "Image/GameScene/Maid/maid_25", Passlevels : 3, Reward : [ "0_23" ], NextID : 13, ShopShow : [ 1, 2, 3, 4, 5, 6, 7, 8 ], DialogueID : 38, RoleDescribe : "" 	},
		{ Id : 13, Name : "锦绣倒水", Path : "Image/GameScene/Maid/maid_26", Passlevels : 4, Reward : [ "0_25" ], NextID : 14, ShopShow : [ 2, 3, 4, 5, 6, 7, 8, 9 ], DialogueID : 0, RoleDescribe : "" 	},
		{ Id : 14, Name : "璎珞拿水桶", Path : "Image/GameScene/Maid/maid_27", Passlevels : 4, Reward : [ "0_27" ], NextID : 15, ShopShow : [ 3, 4, 5, 6, 7, 8, 9, 10 ], DialogueID : 40, RoleDescribe : "" 	},
		{ Id : 15, Name : "拿被子的璎珞", Path : "Image/GameScene/Maid/maid_28", Passlevels : 4, Reward : [ "0_29" ], NextID : 16, ShopShow : [ 4, 5, 6, 7, 8, 9, 10, 11 ], DialogueID : 41, RoleDescribe : "" 	},
		{ Id : 16, Name : "湿身锦绣", Path : "Image/GameScene/Maid/maid_29", Passlevels : 4, Reward : [ "0_31" ], NextID : 17, ShopShow : [ 5, 6, 7, 8, 9, 10, 11, 12 ], DialogueID : 42, RoleDescribe : "" 	},
		{ Id : 17, Name : "璎珞发火", Path : "Image/GameScene/Maid/maid_30", Passlevels : 4, Reward : [ "0_33" ], NextID : 18, ShopShow : [ 6, 7, 8, 9, 10, 11, 12, 13 ], DialogueID : 43, RoleDescribe : "" 	},
		{ Id : 18, Name : "方姑姑", Path : "Image/GameScene/Maid/maid_31", Passlevels : 4, Reward : [ "0_35" ], NextID : 19, ShopShow : [ 7, 8, 9, 10, 11, 12, 13, 14 ], DialogueID : 44, RoleDescribe : "" 	},
		{ Id : 19, Name : "吉祥吃面", Path : "Image/GameScene/Maid/maid_32", Passlevels : 5, Reward : [ "0_37" ], NextID : 20, ShopShow : [ 8, 9, 10, 11, 12, 13, 14, 15 ], DialogueID : 0, RoleDescribe : "" 	},
		{ Id : 20, Name : "吉祥手帕", Path : "Image/GameScene/Maid/maid_33", Passlevels : 5, Reward : [ "0_39" ], NextID : 21, ShopShow : [ 9, 10, 11, 12, 13, 14, 15, 16 ], DialogueID : 52, RoleDescribe : "" 	},
		{ Id : 21, Name : "吉祥被抓", Path : "Image/GameScene/Maid/maid_34", Passlevels : 5, Reward : [ "0_41" ], NextID : 22, ShopShow : [ 10, 11, 12, 13, 14, 15, 16, 17 ], DialogueID : 53, RoleDescribe : "" 	},
		{ Id : 22, Name : "璎珞绣常服", Path : "Image/GameScene/Maid/maid_35", Passlevels : 5, Reward : [ "0_43" ], NextID : 23, ShopShow : [ 11, 12, 13, 14, 15, 16, 17, 18 ], DialogueID : 54, RoleDescribe : "" 	},
		{ Id : 23, Name : "皇帝穿常服", Path : "Image/GameScene/Maid/maid_36", Passlevels : 5, Reward : [ "0_45" ], NextID : 24, ShopShow : [ 12, 13, 14, 15, 16, 17, 18, 19 ], DialogueID : 55, RoleDescribe : "" 	},
		{ Id : 24, Name : "玲珑盒饭", Path : "Image/GameScene/Maid/maid_37", Passlevels : 5, Reward : [ "0_47" ], NextID : 25, ShopShow : [ 13, 14, 15, 16, 17, 18, 19, 20 ], DialogueID : 56, RoleDescribe : "" 	},
		{ Id : 25, Name : "尔晴", Path : "Image/GameScene/Maid/maid_19", Passlevels : 5, Reward : [ "0_49" ], NextID : 26, ShopShow : [ 14, 15, 16, 17, 18, 19, 20, 21 ], DialogueID : 31, RoleDescribe : "" 	},
		{ Id : 26, Name : "玉如意", Path : "Image/GameScene/Maid/maid_7", Passlevels : 6, Reward : [ "0_51" ], NextID : 27, ShopShow : [ 15, 16, 17, 18, 19, 20, 21, 22 ], DialogueID : 0, RoleDescribe : "" 	},
		{ Id : 27, Name : "暖玉", Path : "Image/GameScene/Maid/maid_8", Passlevels : 6, Reward : [ "0_53" ], NextID : 28, ShopShow : [ 16, 17, 18, 19, 20, 21, 22, 23 ], DialogueID : 8, RoleDescribe : "" 	},
		{ Id : 28, Name : "宝石盆景", Path : "Image/GameScene/Maid/maid_9", Passlevels : 6, Reward : [ "0_55" ], NextID : 29, ShopShow : [ 17, 18, 19, 20, 21, 22, 23, 24 ], DialogueID : 9, RoleDescribe : "" 	},
		{ Id : 29, Name : "送子观音", Path : "Image/GameScene/Maid/maid_10", Passlevels : 6, Reward : [ "0_57" ], NextID : 30, ShopShow : [ 18, 19, 20, 21, 22, 23, 24, 25 ], DialogueID : 10, RoleDescribe : "" 	},
		{ Id : 30, Name : "报时妆奁", Path : "Image/GameScene/Maid/maid_11", Passlevels : 6, Reward : [ "0_59" ], NextID : 31, ShopShow : [ 19, 20, 21, 22, 23, 24, 25, 26 ], DialogueID : 11, RoleDescribe : "" 	},
		{ Id : 31, Name : "璎珞献凤袍", Path : "Image/GameScene/Maid/maid_12", Passlevels : 6, Reward : [ "0_61" ], NextID : 32, ShopShow : [ 20, 21, 22, 23, 24, 25, 26, 27 ], DialogueID : 12, RoleDescribe : "" 	},
		{ Id : 32, Name : "珍珠", Path : "Image/GameScene/Maid/maid_13", Passlevels : 7, Reward : [ "0_63" ], NextID : 33, ShopShow : [ 21, 22, 23, 24, 25, 26, 27, 28 ], DialogueID : 0, RoleDescribe : "" 	},
		{ Id : 33, Name : "玛瑙", Path : "Image/GameScene/Maid/maid_14", Passlevels : 7, Reward : [ "0_65" ], NextID : 34, ShopShow : [ 22, 23, 24, 25, 26, 27, 28, 29 ], DialogueID : 26, RoleDescribe : "" 	},
		{ Id : 34, Name : "翡翠", Path : "Image/GameScene/Maid/maid_15", Passlevels : 7, Reward : [ "0_67" ], NextID : 35, ShopShow : [ 23, 24, 25, 26, 27, 28, 29, 30 ], DialogueID : 27, RoleDescribe : "" 	},
		{ Id : 35, Name : "琥珀", Path : "Image/GameScene/Maid/maid_16", Passlevels : 7, Reward : [ "0_69" ], NextID : 36, ShopShow : [ 24, 25, 26, 27, 28, 29, 30, 31 ], DialogueID : 28, RoleDescribe : "" 	},
		{ Id : 36, Name : "明玉", Path : "Image/GameScene/Maid/maid_17", Passlevels : 7, Reward : [ "0_71" ], NextID : 37, ShopShow : [ 25, 26, 27, 28, 29, 30, 31, 32 ], DialogueID : 29, RoleDescribe : "" 	},
		{ Id : 37, Name : "璎珞", Path : "Image/GameScene/Maid/maid_18", Passlevels : 7, Reward : [ "0_73" ], NextID : 38, ShopShow : [ 26, 27, 28, 29, 30, 31, 32, 33 ], DialogueID : 30, RoleDescribe : "" 	},
		{ Id : 38, Name : "尔晴", Path : "Image/GameScene/Maid/maid_19", Passlevels : 7, Reward : [ "0_75" ], NextID : 39, ShopShow : [ 27, 28, 29, 30, 31, 32, 33, 34 ], DialogueID : 31, RoleDescribe : "" 	},
		{ Id : 39, Name : "牡丹图", Path : "Image/GameScene/Maid/maid_20", Passlevels : 8, Reward : [ "0_77" ], NextID : 40, ShopShow : [ 28, 29, 30, 31, 32, 33, 34, 35 ], DialogueID : 0, RoleDescribe : "" 	},
		{ Id : 40, Name : "金鸡图", Path : "Image/GameScene/Maid/maid_21", Passlevels : 8, Reward : [ "0_79" ], NextID : 41, ShopShow : [ 29, 30, 31, 32, 33, 34, 35, 36 ], DialogueID : 34, RoleDescribe : "" 	},
		{ Id : 41, Name : "吉祥哭", Path : "Image/GameScene/Maid/maid_22", Passlevels : 8, Reward : [ "0_81" ], NextID : 42, ShopShow : [ 30, 31, 32, 33, 34, 35, 36, 37 ], DialogueID : 35, RoleDescribe : "" 	},
		{ Id : 42, Name : "璎珞翘舌", Path : "Image/GameScene/Maid/maid_23", Passlevels : 8, Reward : [ "0_83" ], NextID : 43, ShopShow : [ 31, 32, 33, 34, 35, 36, 37, 38 ], DialogueID : 36, RoleDescribe : "" 	},
		{ Id : 43, Name : "张嬷嬷", Path : "Image/GameScene/Maid/maid_24", Passlevels : 8, Reward : [ "0_85" ], NextID : 44, ShopShow : [ 32, 33, 34, 35, 36, 37, 38, 39 ], DialogueID : 37, RoleDescribe : "" 	},
		{ Id : 44, Name : "吴总管", Path : "Image/GameScene/Maid/maid_25", Passlevels : 8, Reward : [ "0_87" ], NextID : 45, ShopShow : [ 33, 34, 35, 36, 37, 38, 39, 40 ], DialogueID : 38, RoleDescribe : "" 	},
		{ Id : 45, Name : "瘦秀女", Path : "Image/GameScene/Maid/maid_1", Passlevels : 9, Reward : [ "0_89" ], NextID : 46, ShopShow : [ 34, 35, 36, 37, 38, 39, 40, 41 ], DialogueID : 0, RoleDescribe : "" 	},
		{ Id : 46, Name : "胖秀女", Path : "Image/GameScene/Maid/maid_2", Passlevels : 9, Reward : [ "0_91" ], NextID : 47, ShopShow : [ 35, 36, 37, 38, 39, 40, 41, 42 ], DialogueID : 2, RoleDescribe : "" 	},
		{ Id : 47, Name : "黑秀女", Path : "Image/GameScene/Maid/maid_3", Passlevels : 9, Reward : [ "0_93" ], NextID : 48, ShopShow : [ 36, 37, 38, 39, 40, 41, 42, 43 ], DialogueID : 3, RoleDescribe : "" 	},
		{ Id : 48, Name : "陆晚晚", Path : "Image/GameScene/Maid/maid_4", Passlevels : 9, Reward : [ "0_95" ], NextID : 49, ShopShow : [ 37, 38, 39, 40, 41, 42, 43, 44 ], DialogueID : 4, RoleDescribe : "" 	},
		{ Id : 49, Name : "纳兰淳雪", Path : "Image/GameScene/Maid/maid_5", Passlevels : 9, Reward : [ "0_97" ], NextID : 50, ShopShow : [ 38, 39, 40, 41, 42, 43, 44, 45 ], DialogueID : 5, RoleDescribe : "" 	},
		{ Id : 50, Name : "乌雅青黛", Path : "Image/GameScene/Maid/maid_6", Passlevels : 9, Reward : [ "0_99" ], NextID : 51, ShopShow : [ 39, 40, 41, 42, 43, 44, 45, 46 ], DialogueID : 6, RoleDescribe : "" 	},
		{ Id : 51, Name : "瘦秀女", Path : "Image/GameScene/Maid/maid_1", Passlevels : 10, Reward : [ "0_101" ], NextID : 52, ShopShow : [ 40, 41, 42, 43, 44, 45, 46, 47 ], DialogueID : 0, RoleDescribe : "" 	},
		{ Id : 52, Name : "胖秀女", Path : "Image/GameScene/Maid/maid_2", Passlevels : 10, Reward : [ "0_103" ], NextID : 53, ShopShow : [ 41, 42, 43, 44, 45, 46, 47, 48 ], DialogueID : 2, RoleDescribe : "" 	},
		{ Id : 53, Name : "黑秀女", Path : "Image/GameScene/Maid/maid_3", Passlevels : 10, Reward : [ "0_105" ], NextID : 54, ShopShow : [ 42, 43, 44, 45, 46, 47, 48, 49 ], DialogueID : 3, RoleDescribe : "" 	},
		{ Id : 54, Name : "陆晚晚", Path : "Image/GameScene/Maid/maid_4", Passlevels : 10, Reward : [ "0_107" ], NextID : 55, ShopShow : [ 43, 44, 45, 46, 47, 48, 49, 50 ], DialogueID : 4, RoleDescribe : "" 	},
		{ Id : 55, Name : "纳兰淳雪", Path : "Image/GameScene/Maid/maid_5", Passlevels : 10, Reward : [ "0_109" ], NextID : 56, ShopShow : [ 44, 45, 46, 47, 48, 49, 50, 51 ], DialogueID : 5, RoleDescribe : "" 	},
		{ Id : 56, Name : "乌雅青黛", Path : "Image/GameScene/Maid/maid_6", Passlevels : 10, Reward : [ "0_111" ], NextID : 57, ShopShow : [ 45, 46, 47, 48, 49, 50, 51, 52 ], DialogueID : 6, RoleDescribe : "" 	},
		{ Id : 57, Name : "牡丹图", Path : "Image/GameScene/Maid/maid_20", Passlevels : 11, Reward : [ "0_113" ], NextID : 58, ShopShow : [ 46, 47, 48, 49, 50, 51, 52, 53 ], DialogueID : 0, RoleDescribe : "" 	},
		{ Id : 58, Name : "金鸡图", Path : "Image/GameScene/Maid/maid_21", Passlevels : 11, Reward : [ "0_115" ], NextID : 59, ShopShow : [ 47, 48, 49, 50, 51, 52, 53, 54 ], DialogueID : 34, RoleDescribe : "" 	},
		{ Id : 59, Name : "吉祥哭", Path : "Image/GameScene/Maid/maid_22", Passlevels : 11, Reward : [ "0_117" ], NextID : 60, ShopShow : [ 48, 49, 50, 51, 52, 53, 54, 55 ], DialogueID : 35, RoleDescribe : "" 	},
		{ Id : 60, Name : "璎珞翘舌", Path : "Image/GameScene/Maid/maid_23", Passlevels : 11, Reward : [ "0_119" ], NextID : 61, ShopShow : [ 49, 50, 51, 52, 53, 54, 55, 56 ], DialogueID : 36, RoleDescribe : "" 	},
		{ Id : 61, Name : "张嬷嬷", Path : "Image/GameScene/Maid/maid_24", Passlevels : 11, Reward : [ "0_121" ], NextID : 62, ShopShow : [ 50, 51, 52, 53, 54, 55, 56, 57 ], DialogueID : 37, RoleDescribe : "" 	},
		{ Id : 62, Name : "吴总管", Path : "Image/GameScene/Maid/maid_25", Passlevels : 11, Reward : [ "0_123" ], NextID : 63, ShopShow : [ 51, 52, 53, 54, 55, 56, 57, 58 ], DialogueID : 38, RoleDescribe : "" 	},
		{ Id : 63, Name : "玉如意", Path : "Image/GameScene/Maid/maid_7", Passlevels : 12, Reward : [ "0_125" ], NextID : 64, ShopShow : [ 52, 53, 54, 55, 56, 57, 58, 59 ], DialogueID : 0, RoleDescribe : "" 	},
		{ Id : 64, Name : "暖玉", Path : "Image/GameScene/Maid/maid_8", Passlevels : 12, Reward : [ "0_127" ], NextID : 65, ShopShow : [ 53, 54, 55, 56, 57, 58, 59, 60 ], DialogueID : 8, RoleDescribe : "" 	},
		{ Id : 65, Name : "宝石盆景", Path : "Image/GameScene/Maid/maid_9", Passlevels : 12, Reward : [ "0_129" ], NextID : 66, ShopShow : [ 54, 55, 56, 57, 58, 59, 60, 61 ], DialogueID : 9, RoleDescribe : "" 	},
		{ Id : 66, Name : "送子观音", Path : "Image/GameScene/Maid/maid_10", Passlevels : 12, Reward : [ "0_131" ], NextID : 67, ShopShow : [ 55, 56, 57, 58, 59, 60, 61, 62 ], DialogueID : 10, RoleDescribe : "" 	},
		{ Id : 67, Name : "报时妆奁", Path : "Image/GameScene/Maid/maid_11", Passlevels : 12, Reward : [ "0_133" ], NextID : 68, ShopShow : [ 56, 57, 58, 59, 60, 61, 62, 63 ], DialogueID : 11, RoleDescribe : "" 	},
		{ Id : 68, Name : "璎珞献凤袍", Path : "Image/GameScene/Maid/maid_12", Passlevels : 12, Reward : [ "0_135" ], NextID : 69, ShopShow : [ 57, 58, 59, 60, 61, 62, 63, 64 ], DialogueID : 12, RoleDescribe : "" 	},
		{ Id : 69, Name : "珍珠", Path : "Image/GameScene/Maid/maid_13", Passlevels : 13, Reward : [ "0_137" ], NextID : 70, ShopShow : [ 58, 59, 60, 61, 62, 63, 64, 65 ], DialogueID : 0, RoleDescribe : "" 	},
		{ Id : 70, Name : "玛瑙", Path : "Image/GameScene/Maid/maid_14", Passlevels : 13, Reward : [ "0_139" ], NextID : 71, ShopShow : [ 59, 60, 61, 62, 63, 64, 65, 66 ], DialogueID : 26, RoleDescribe : "" 	},
		{ Id : 71, Name : "翡翠", Path : "Image/GameScene/Maid/maid_15", Passlevels : 13, Reward : [ "0_141" ], NextID : 72, ShopShow : [ 60, 61, 62, 63, 64, 65, 66, 67 ], DialogueID : 27, RoleDescribe : "" 	},
		{ Id : 72, Name : "琥珀", Path : "Image/GameScene/Maid/maid_16", Passlevels : 13, Reward : [ "0_143" ], NextID : 73, ShopShow : [ 61, 62, 63, 64, 65, 66, 67, 68 ], DialogueID : 28, RoleDescribe : "" 	},
		{ Id : 73, Name : "明玉", Path : "Image/GameScene/Maid/maid_17", Passlevels : 13, Reward : [ "0_145" ], NextID : 74, ShopShow : [ 62, 63, 64, 65, 66, 67, 68, 69 ], DialogueID : 29, RoleDescribe : "" 	},
		{ Id : 74, Name : "璎珞", Path : "Image/GameScene/Maid/maid_18", Passlevels : 13, Reward : [ "0_147" ], NextID : 75, ShopShow : [ 63, 64, 65, 66, 67, 68, 69, 70 ], DialogueID : 30, RoleDescribe : "" 	},
		{ Id : 75, Name : "尔晴", Path : "Image/GameScene/Maid/maid_19", Passlevels : 13, Reward : [ "0_149" ], NextID : 0, ShopShow : [ 64, 65, 66, 67, 68, 69, 70, 71 ], DialogueID : 31, RoleDescribe : "" 	}
	]


// Id
export var TMaidLevelById : game.Dictionary<table.ITMaidLevelDefine> = {}
function readTMaidLevelById(){
  for(let rec of TMaidLevel) {
    TMaidLevelById[rec.Id] = rec; 
  }
}
readTMaidLevelById();
}

