// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var PalacePersonnel : table.IPalacePersonnelDefine[] = [
		{ Id : 1, Name : "愉妃", Path : "Image/GameScene/halfbody/17", WholeBodyPath : "Image/GameScene/wholebody/master_01", RoleDescribe : "性格比较懦弱。" 	},
		{ Id : 2, Name : "高宁馨", Path : "Image/GameScene/halfbody/12", WholeBodyPath : "Image/GameScene/wholebody/master_02", RoleDescribe : "为人嚣张跋扈。" 	},
		{ Id : 3, Name : "富察容音", Path : "Image/GameScene/halfbody/1", WholeBodyPath : "Image/GameScene/wholebody/master_03", RoleDescribe : "乾隆的结发妻子。" 	},
		{ Id : 4, Name : "辉发那拉", Path : "Image/GameScene/halfbody/13", WholeBodyPath : "Image/GameScene/wholebody/master_04", RoleDescribe : "乾隆的第二任皇后。" 	},
		{ Id : 5, Name : "魏璎珞", Path : "Image/GameScene/halfbody/4", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 6, Name : "苏静好", Path : "Image/GameScene/halfbody/13", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 7, Name : "顺嫔", Path : "Image/GameScene/halfbody/1", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 8, Name : "嘉嫔", Path : "Image/GameScene/halfbody/12", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 9, Name : "纳兰淳雪", Path : "Image/GameScene/halfbody/14", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 10, Name : "陆晚晚", Path : "Image/GameScene/halfbody/6", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 11, Name : "容妃", Path : "Image/GameScene/halfbody/12", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 12, Name : "怡嫔", Path : "Image/GameScene/halfbody/13", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 100, Name : "夏荷", Path : "Image/GameScene/Maid/maid_15", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 101, Name : "春然", Path : "Image/GameScene/Maid/maid_16", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 102, Name : "芳草", Path : "Image/GameScene/Maid/maid_17", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 103, Name : "芷荷", Path : "Image/GameScene/Maid/maid_15", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 104, Name : "香卉", Path : "Image/GameScene/Maid/maid_16", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 105, Name : "秋春", Path : "Image/GameScene/Maid/maid_17", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 200, Name : "莫心", Path : "Image/GameScene/Maid/maid_15", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 201, Name : "墨兰", Path : "Image/GameScene/Maid/maid_16", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 202, Name : "芝兰", Path : "Image/GameScene/Maid/maid_19", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 203, Name : "晓兰", Path : "Image/GameScene/Maid/maid_15", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 204, Name : "绮兰", Path : "Image/GameScene/Maid/maid_16", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 205, Name : "听兰", Path : "Image/GameScene/Maid/maid_19", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 300, Name : "明玉", Path : "Image/GameScene/Maid/maid_17", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 301, Name : "尔晴", Path : "Image/GameScene/Maid/maid_19", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 302, Name : "璎珞", Path : "Image/GameScene/Maid/maid_18", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 303, Name : "珍珠", Path : "Image/GameScene/Maid/maid_17", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 304, Name : "翡翠", Path : "Image/GameScene/Maid/maid_19", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 305, Name : "玛瑙", Path : "Image/GameScene/Maid/maid_18", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 400, Name : "宛儿", Path : "Image/GameScene/Maid/maid_17", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 401, Name : "珍儿", Path : "Image/GameScene/Maid/maid_19", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 402, Name : "盼儿", Path : "Image/GameScene/Maid/maid_18", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 403, Name : "友儿", Path : "Image/GameScene/Maid/maid_17", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 404, Name : "巧儿", Path : "Image/GameScene/Maid/maid_19", WholeBodyPath : "", RoleDescribe : "" 	},
		{ Id : 405, Name : "云儿", Path : "Image/GameScene/Maid/maid_18", WholeBodyPath : "", RoleDescribe : "" 	}
	]


// Id
export var PalacePersonnelById : game.Dictionary<table.IPalacePersonnelDefine> = {}
function readPalacePersonnelById(){
  for(let rec of PalacePersonnel) {
    PalacePersonnelById[rec.Id] = rec; 
  }
}
readPalacePersonnelById();
}

