// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var PalacePersonnel : table.IPalacePersonnelDefine[] = [
		{ Id : 1, Name : "富察容音", Path : "Image/GameScene/halfbody/1", RoleDescribe : "乾隆的结发妻子。" 	},
		{ Id : 2, Name : "高宁馨", Path : "Image/GameScene/halfbody/12", RoleDescribe : "为人嚣张跋扈" 	},
		{ Id : 3, Name : "辉发那拉", Path : "Image/GameScene/halfbody/13", RoleDescribe : "乾隆的第二任皇后" 	},
		{ Id : 4, Name : "魏璎珞", Path : "Image/GameScene/halfbody/4", RoleDescribe : "" 	},
		{ Id : 5, Name : "愉妃", Path : "Image/GameScene/halfbody/1", RoleDescribe : "" 	},
		{ Id : 6, Name : "苏静好", Path : "Image/GameScene/halfbody/13", RoleDescribe : "" 	},
		{ Id : 7, Name : "顺嫔", Path : "Image/GameScene/halfbody/1", RoleDescribe : "" 	},
		{ Id : 8, Name : "嘉嫔", Path : "Image/GameScene/halfbody/12", RoleDescribe : "" 	},
		{ Id : 9, Name : "纳兰淳雪", Path : "Image/GameScene/halfbody/14", RoleDescribe : "" 	},
		{ Id : 10, Name : "陆晚晚", Path : "Image/GameScene/halfbody/6", RoleDescribe : "" 	},
		{ Id : 11, Name : "容妃", Path : "Image/GameScene/halfbody/12", RoleDescribe : "" 	},
		{ Id : 12, Name : "怡嫔", Path : "Image/GameScene/halfbody/13", RoleDescribe : "" 	},
		{ Id : 100, Name : "明玉", Path : "Image/GameScene/Maid/maid_17", RoleDescribe : "" 	},
		{ Id : 101, Name : "尔晴", Path : "Image/GameScene/Maid/maid_19", RoleDescribe : "" 	},
		{ Id : 102, Name : "璎珞", Path : "Image/GameScene/Maid/maid_18", RoleDescribe : "" 	},
		{ Id : 200, Name : "夏荷", Path : "Image/GameScene/Maid/maid_15", RoleDescribe : "" 	},
		{ Id : 201, Name : "春然", Path : "Image/GameScene/Maid/maid_16", RoleDescribe : "" 	},
		{ Id : 202, Name : "芳草", Path : "Image/GameScene/Maid/maid_17", RoleDescribe : "" 	},
		{ Id : 300, Name : "莫心", Path : "Image/GameScene/Maid/maid_15", RoleDescribe : "" 	},
		{ Id : 301, Name : "墨兰", Path : "Image/GameScene/Maid/maid_16", RoleDescribe : "" 	},
		{ Id : 302, Name : "芝兰", Path : "Image/GameScene/Maid/maid_19", RoleDescribe : "" 	}
	]


// Id
export var PalacePersonnelById : game.Dictionary<table.IPalacePersonnelDefine> = {}
function readPalacePersonnelById(){
  for(let rec of PalacePersonnel) {
    PalacePersonnelById[rec.Id] = rec; 
  }
}
readPalacePersonnelById();
}

