// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var PalaceMapMasterLevels : table.IPalaceMapMasterLevelsDefine[] = [
		{ Id : 1, MasterId : 1, Level : 1, LevelupCost : [ "1001_1", "1002_2" ], WaitTime : 6400 	},
		{ Id : 2, MasterId : 1, Level : 2, LevelupCost : [ "1001_1", "1002_3" ], WaitTime : 3200 	},
		{ Id : 3, MasterId : 1, Level : 3, LevelupCost : [ "1001_1", "1002_4" ], WaitTime : 3000 	},
		{ Id : 4, MasterId : 1, Level : 4, LevelupCost : [ "1001_1", "1002_5" ], WaitTime : 6400 	},
		{ Id : 5, MasterId : 1, Level : 5, LevelupCost : [ "1001_1", "1002_6" ], WaitTime : 3200 	},
		{ Id : 6, MasterId : 1, Level : 6, LevelupCost : [ "1001_1", "1002_7" ], WaitTime : 3000 	},
		{ Id : 7, MasterId : 2, Level : 1, LevelupCost : [ "1001_1", "1002_8" ], WaitTime : 6400 	},
		{ Id : 8, MasterId : 2, Level : 2, LevelupCost : [ "1001_1", "1002_9" ], WaitTime : 3200 	},
		{ Id : 9, MasterId : 2, Level : 3, LevelupCost : [ "1001_1", "1002_10" ], WaitTime : 3000 	},
		{ Id : 10, MasterId : 2, Level : 4, LevelupCost : [ "1001_1", "1002_11" ], WaitTime : 6400 	},
		{ Id : 11, MasterId : 2, Level : 5, LevelupCost : [ "1001_1", "1002_12" ], WaitTime : 3200 	},
		{ Id : 12, MasterId : 2, Level : 6, LevelupCost : [ "1001_1", "1002_13" ], WaitTime : 3000 	},
		{ Id : 13, MasterId : 3, Level : 1, LevelupCost : [ "1001_1", "1002_14" ], WaitTime : 6400 	},
		{ Id : 14, MasterId : 3, Level : 2, LevelupCost : [ "1001_1", "1002_15" ], WaitTime : 3200 	},
		{ Id : 15, MasterId : 3, Level : 3, LevelupCost : [ "1001_1", "1002_16" ], WaitTime : 3000 	},
		{ Id : 16, MasterId : 3, Level : 4, LevelupCost : [ "1001_1", "1002_17" ], WaitTime : 6400 	},
		{ Id : 17, MasterId : 3, Level : 5, LevelupCost : [ "1001_1", "1002_18" ], WaitTime : 3200 	}
	]


// Id
export var PalaceMapMasterLevelsById : game.Dictionary<table.IPalaceMapMasterLevelsDefine> = {}
function readPalaceMapMasterLevelsById(){
  for(let rec of PalaceMapMasterLevels) {
    PalaceMapMasterLevelsById[rec.Id] = rec; 
  }
}
readPalaceMapMasterLevelsById();
}

