// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var PalaceMapMaid : table.IPalaceMapMaidDefine[] = [
		{ Id : 300, OpenLevel : 1, UnlockPrice : [ "1_76", "0_0000" ], GoldAddition : [ "0_76" ], ItemGroup : [ "10001_1", "20001_1", "20002_1", "20003_1", "20004_1", "20005_1", "20006_1" ], ItemProb : 10000, Describe : "主要产出御膳道具" 	},
		{ Id : 301, OpenLevel : 2, UnlockPrice : [ "1_95", "0_0000" ], GoldAddition : [ "0_95" ], ItemGroup : [ "30001_1", "30002_1", "30003_1", "30004_1", "30005_1", "30006_1", "30007_1", "30008_1" ], ItemProb : 10000, Describe : "主要产出御品道具" 	},
		{ Id : 302, OpenLevel : 3, UnlockPrice : [ "1_190", "0_0000" ], GoldAddition : [ "0_190" ], ItemGroup : [ "40001_1", "40002_1", "40003_1", "40004_1", "40005_1" ], ItemProb : 10000, Describe : "主要产出服装道具" 	},
		{ Id : 303, OpenLevel : 4, UnlockPrice : [ "1_190", "0_0000" ], GoldAddition : [ "0_190" ], ItemGroup : [ "10001_1", "20001_1", "20002_1", "20003_1", "20004_1", "20005_1", "20006_1" ], ItemProb : 10000, Describe : "主要产出御膳道具" 	},
		{ Id : 304, OpenLevel : 5, UnlockPrice : [ "1_190", "0_0000" ], GoldAddition : [ "0_190" ], ItemGroup : [ "30001_1", "30002_1", "30003_1", "30004_1", "30005_1", "30006_1", "30007_1", "30008_1" ], ItemProb : 10000, Describe : "主要产出御品道具" 	},
		{ Id : 305, OpenLevel : 6, UnlockPrice : [ "1_190", "0_0000" ], GoldAddition : [ "0_190" ], ItemGroup : [ "40001_1", "40002_1", "40003_1", "40004_1", "40005_1" ], ItemProb : 10000, Describe : "主要产出服装道具" 	},
		{ Id : 200, OpenLevel : 1, UnlockPrice : [ "1_276", "0_0000" ], GoldAddition : [ "0_276" ], ItemGroup : [ "10001_1", "20001_1", "20002_1", "20003_1", "20004_1", "20005_1", "20006_1" ], ItemProb : 10000, Describe : "主要产出御膳道具" 	},
		{ Id : 201, OpenLevel : 2, UnlockPrice : [ "1_345", "0_0000" ], GoldAddition : [ "0_345" ], ItemGroup : [ "30001_1", "30002_1", "30003_1", "30004_1", "30005_1", "30006_1", "30007_1", "30008_1" ], ItemProb : 10000, Describe : "主要产出御品道具" 	},
		{ Id : 202, OpenLevel : 3, UnlockPrice : [ "1_690", "0_0000" ], GoldAddition : [ "0_690" ], ItemGroup : [ "40001_1", "40002_1", "40003_1", "40004_1", "40005_1" ], ItemProb : 10000, Describe : "主要产出服装道具" 	},
		{ Id : 203, OpenLevel : 4, UnlockPrice : [ "1_690", "0_0000" ], GoldAddition : [ "0_690" ], ItemGroup : [ "10001_1", "20001_1", "20002_1", "20003_1", "20004_1", "20005_1", "20006_1" ], ItemProb : 10000, Describe : "主要产出御膳道具" 	},
		{ Id : 204, OpenLevel : 5, UnlockPrice : [ "1_690", "0_0000" ], GoldAddition : [ "0_690" ], ItemGroup : [ "30001_1", "30002_1", "30003_1", "30004_1", "30005_1", "30006_1", "30007_1", "30008_1" ], ItemProb : 10000, Describe : "主要产出御品道具" 	},
		{ Id : 205, OpenLevel : 6, UnlockPrice : [ "1_690", "0_0000" ], GoldAddition : [ "0_690" ], ItemGroup : [ "40001_1", "40002_1", "40003_1", "40004_1", "40005_1" ], ItemProb : 10000, Describe : "主要产出服装道具" 	},
		{ Id : 100, OpenLevel : 1, UnlockPrice : [ "1_472", "0_0000" ], GoldAddition : [ "0_472" ], ItemGroup : [ "10001_1", "20001_1", "20002_1", "20003_1", "20004_1", "20005_1", "20006_1" ], ItemProb : 10000, Describe : "主要产出御膳道具" 	},
		{ Id : 101, OpenLevel : 2, UnlockPrice : [ "1_590", "0_0000" ], GoldAddition : [ "0_590" ], ItemGroup : [ "30001_1", "30002_1", "30003_1", "30004_1", "30005_1", "30006_1", "30007_1", "30008_1" ], ItemProb : 10000, Describe : "主要产出御品道具" 	},
		{ Id : 102, OpenLevel : 3, UnlockPrice : [ "1_1180", "0_0000" ], GoldAddition : [ "0_1180" ], ItemGroup : [ "40001_1", "40002_1", "40003_1", "40004_1", "40005_1" ], ItemProb : 10000, Describe : "主要产出服装道具" 	},
		{ Id : 103, OpenLevel : 4, UnlockPrice : [ "1_1180", "0_0000" ], GoldAddition : [ "0_1180" ], ItemGroup : [ "10001_1", "20001_1", "20002_1", "20003_1", "20004_1", "20005_1", "20006_1" ], ItemProb : 10000, Describe : "主要产出御膳道具" 	},
		{ Id : 104, OpenLevel : 5, UnlockPrice : [ "1_1180", "0_0000" ], GoldAddition : [ "0_1180" ], ItemGroup : [ "30001_1", "30002_1", "30003_1", "30004_1", "30005_1", "30006_1", "30007_1", "30008_1" ], ItemProb : 10000, Describe : "主要产出御品道具" 	},
		{ Id : 105, OpenLevel : 6, UnlockPrice : [ "1_1180", "0_0000" ], GoldAddition : [ "0_1180" ], ItemGroup : [ "40001_1", "40002_1", "40003_1", "40004_1", "40005_1" ], ItemProb : 10000, Describe : "主要产出服装道具" 	}
	]


// Id
export var PalaceMapMaidById : game.Dictionary<table.IPalaceMapMaidDefine> = {}
function readPalaceMapMaidById(){
  for(let rec of PalaceMapMaid) {
    PalaceMapMaidById[rec.Id] = rec; 
  }
}
readPalaceMapMaidById();
}

