// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var PalaceMapMaid : table.IPalaceMapMaidDefine[] = [
		{ Id : 17, OpenLevel : 1, UnlockPrice : 1000, GoldAddition : 1, ItemGroup : [ "1001_1", "1002_1" ], ItemProb : 1000, Describe : "主要产出御膳道具" 	},
		{ Id : 19, OpenLevel : 2, UnlockPrice : 20000, GoldAddition : 2, ItemGroup : [ "1001_1", "1002_1" ], ItemProb : 1000, Describe : "主要产出御品道具" 	},
		{ Id : 18, OpenLevel : 3, UnlockPrice : 400000, GoldAddition : 3, ItemGroup : [ "1001_1", "1002_1" ], ItemProb : 1000, Describe : "主要产出服装道具" 	}
	]


// Id
export var PalaceMapMaidById : game.Dictionary<table.IPalaceMapMaidDefine> = {}
function readPalaceMapMaidById(){
  for(let rec of PalaceMapMaid) {
    PalaceMapMaidById[rec.Id] = rec; 
  }
}
readPalaceMapMaidById();
}

