// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var PalaceMap : table.IPalaceMapDefine[] = [
		{ Id : 1, Name : "永和宫", BannerPath : "Image/GameScene/Palace/image_palaceCard1", UlockPassId : 2, x : 300, y : 122, Headpath : "Image/GameScene/halfbody/13", Master : 3, Maids : [ 300, 301, 302, 303, 304, 305 ], MaidsXY : [ "-222,-106", "0,-106", "222,-106", "-222,-350", "0,-350", "222,-350" ] 	},
		{ Id : 2, Name : "储秀宫", BannerPath : "Image/GameScene/Palace/image_palaceCard2", UlockPassId : 9, x : -165, y : 242, Headpath : "Image/GameScene/halfbody/12", Master : 2, Maids : [ 200, 201, 202, 203, 204, 205 ], MaidsXY : [ "-222,-106", "0,-106", "222,-106", "-222,-350", "0,-350", "222,-350" ] 	},
		{ Id : 3, Name : "长春宫", BannerPath : "Image/GameScene/Palace/image_palaceCard3", UlockPassId : 13, x : -300, y : 122, Headpath : "Image/GameScene/halfbody/1", Master : 1, Maids : [ 100, 101, 102, 103, 104, 105 ], MaidsXY : [ "-222,-106", "0,-106", "222,-106", "-222,-350", "0,-350", "222,-350" ] 	},
		{ Id : 4, Name : "钟粹宫", BannerPath : "Image/GameScene/Palace/image_palaceCard3", UlockPassId : 99, x : 165, y : 242, Headpath : "Image/GameScene/halfbody/1", Master : 6, Maids : [ 100, 101, 102, 103, 104, 105 ], MaidsXY : [ "-222,-106", "0,-106", "222,-106", "-222,-350", "0,-350", "222,-350" ] 	},
		{ Id : 5, Name : "承乾宫", BannerPath : "Image/GameScene/Palace/image_palaceCard3", UlockPassId : 99, x : 165, y : 122, Headpath : "Image/GameScene/halfbody/1", Master : 5, Maids : [ 100, 101, 102, 103, 104, 105 ], MaidsXY : [ "-222,-106", "0,-106", "222,-106", "-222,-350", "0,-350", "222,-350" ] 	},
		{ Id : 6, Name : "景仁宫", BannerPath : "Image/GameScene/Palace/image_palaceCard3", UlockPassId : 99, x : 165, y : 10, Headpath : "Image/GameScene/halfbody/1", Master : 9, Maids : [ 100, 101, 102, 103, 104, 105 ], MaidsXY : [ "-222,-106", "0,-106", "222,-106", "-222,-350", "0,-350", "222,-350" ] 	},
		{ Id : 7, Name : "延禧宫", BannerPath : "Image/GameScene/Palace/image_palaceCard3", UlockPassId : 99, x : 300, y : 10, Headpath : "Image/GameScene/halfbody/1", Master : 4, Maids : [ 100, 101, 102, 103, 104, 105 ], MaidsXY : [ "-222,-106", "0,-106", "222,-106", "-222,-350", "0,-350", "222,-350" ] 	}
	]


// Id
export var PalaceMapById : game.Dictionary<table.IPalaceMapDefine> = {}
function readPalaceMapById(){
  for(let rec of PalaceMap) {
    PalaceMapById[rec.Id] = rec; 
  }
}
readPalaceMapById();
}

