// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var PalaceMap : table.IPalaceMapDefine[] = [
		{ Id : 1, Name : "永和宫", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 1, x : -300, y : 122, Headpath : "Image/Head/1" 	},
		{ Id : 2, Name : "储秀宫", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 3, x : 165, y : 242, Headpath : "Image/Head/1" 	},
		{ Id : 3, Name : "长春宫", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 2, x : 300, y : 122, Headpath : "Image/Head/1" 	},
		{ Id : 4, Name : "钟粹宫", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 99, x : -165, y : 242, Headpath : "Image/Head/1" 	},
		{ Id : 5, Name : "承乾宫", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 99, x : -165, y : 122, Headpath : "Image/Head/1" 	},
		{ Id : 6, Name : "景仁宫", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 99, x : -165, y : 10, Headpath : "Image/Head/1" 	},
		{ Id : 7, Name : "延禧宫", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 99, x : -300, y : 10, Headpath : "Image/Head/1" 	},
		{ Id : 8, Name : "咸福宫", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 99, x : 300, y : 242, Headpath : "Image/Head/1" 	},
		{ Id : 9, Name : "翊坤宫", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 99, x : 165, y : 122, Headpath : "Image/Head/1" 	},
		{ Id : 10, Name : "启祥宫", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 99, x : 300, y : 10, Headpath : "Image/Head/1" 	},
		{ Id : 11, Name : "永寿宫", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 99, x : 165, y : 10, Headpath : "Image/Head/1" 	},
		{ Id : 12, Name : "景阳宫", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 99, x : -300, y : 242, Headpath : "Image/Head/1" 	},
		{ Id : 13, Name : "乾清宫", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 99, x : 0, y : -63, Headpath : "Image/Head/1" 	},
		{ Id : 14, Name : "坤宁宫", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 99, x : 0, y : 143, Headpath : "Image/Head/1" 	},
		{ Id : 15, Name : "御花园", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 99, x : 0, y : -342, Headpath : "Image/Head/1" 	},
		{ Id : 16, Name : "养心殿", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 99, x : 225, y : -145, Headpath : "Image/Head/1" 	},
		{ Id : 17, Name : "侍卫处", UlockPath : "Image/GameScene/Palace/image_palaceunlock1", Lockpath : "Image/GameScene/Palace/image_palacelock1", UlockPassId : 99, x : -225, y : -145, Headpath : "Image/Head/1" 	}
	]


// Id
export var PalaceMapById : game.Dictionary<table.IPalaceMapDefine> = {}
function readPalaceMapById(){
  for(let rec of PalaceMap) {
    PalaceMapById[rec.Id] = rec; 
  }
}
readPalaceMapById();
}

