// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var PalaceMapMaid : table.IPalaceMapMaidDefine[] = [
		{ Id : 100, OpenLevel : 1, UnlockPrice : [ "0_1" ], GoldAddition : [ "0_400" ], ItemGroup : [ "20001_1", "20002_1", "20004_1", "20005_1", "20006_1" ], ItemProb : 10000, Describe : "主要产出御膳道具" 	},
		{ Id : 101, OpenLevel : 2, UnlockPrice : [ "1_100", "0_0" ], GoldAddition : [ "0_1000" ], ItemGroup : [ "30001_1", "30002_1", "30003_1", "30004_1", "30005_1", "30006_1", "30007_1", "30008_1" ], ItemProb : 10000, Describe : "主要产出御品道具" 	},
		{ Id : 102, OpenLevel : 3, UnlockPrice : [ "1_160", "0_0" ], GoldAddition : [ "0_1600" ], ItemGroup : [ "40001_1", "40002_1", "40003_1", "40004_1", "40005_1" ], ItemProb : 10000, Describe : "主要产出服装道具" 	},
		{ Id : 103, OpenLevel : 4, UnlockPrice : [ "1_310", "0_0" ], GoldAddition : [ "0_3100" ], ItemGroup : [ "10001_1", "20001_1", "20002_1", "20003_1", "20004_1", "20005_1", "20006_1" ], ItemProb : 10000, Describe : "主要产出御膳道具" 	},
		{ Id : 104, OpenLevel : 5, UnlockPrice : [ "1_550", "0_0" ], GoldAddition : [ "0_5500" ], ItemGroup : [ "30001_1", "30002_1", "30003_1", "30004_1", "30005_1", "30006_1", "30007_1", "30008_1" ], ItemProb : 10000, Describe : "主要产出御品道具" 	},
		{ Id : 105, OpenLevel : 6, UnlockPrice : [ "1_850", "0_0" ], GoldAddition : [ "0_8500" ], ItemGroup : [ "40001_1", "40002_1", "40003_1", "40004_1", "40005_1" ], ItemProb : 10000, Describe : "主要产出服装道具" 	},
		{ Id : 200, OpenLevel : 1, UnlockPrice : [ "1_800", "0_0" ], GoldAddition : [ "0_8000" ], ItemGroup : [ "10001_1", "20001_1", "20002_1", "20003_1", "20004_1", "20005_1", "20006_1" ], ItemProb : 10000, Describe : "主要产出御膳道具" 	},
		{ Id : 201, OpenLevel : 2, UnlockPrice : [ "1_2000", "0_0" ], GoldAddition : [ "1_2", "0_0" ], ItemGroup : [ "30001_1", "30002_1", "30003_1", "30004_1", "30005_1", "30006_1", "30007_1", "30008_1" ], ItemProb : 10000, Describe : "主要产出御品道具" 	},
		{ Id : 202, OpenLevel : 3, UnlockPrice : [ "1_3200", "0_0" ], GoldAddition : [ "1_3", "0_2000" ], ItemGroup : [ "40001_1", "40002_1", "40003_1", "40004_1", "40005_1" ], ItemProb : 10000, Describe : "主要产出服装道具" 	},
		{ Id : 203, OpenLevel : 4, UnlockPrice : [ "1_6200", "0_0" ], GoldAddition : [ "1_6", "0_2000" ], ItemGroup : [ "10001_1", "20001_1", "20002_1", "20003_1", "20004_1", "20005_1", "20006_1" ], ItemProb : 10000, Describe : "主要产出御膳道具" 	},
		{ Id : 204, OpenLevel : 5, UnlockPrice : [ "2_1", "1_1000" ], GoldAddition : [ "1_11", "0_0" ], ItemGroup : [ "30001_1", "30002_1", "30003_1", "30004_1", "30005_1", "30006_1", "30007_1", "30008_1" ], ItemProb : 10000, Describe : "主要产出御品道具" 	},
		{ Id : 205, OpenLevel : 6, UnlockPrice : [ "2_1", "1_7000" ], GoldAddition : [ "1_17", "0_0" ], ItemGroup : [ "40001_1", "40002_1", "40003_1", "40004_1", "40005_1" ], ItemProb : 10000, Describe : "主要产出服装道具" 	},
		{ Id : 300, OpenLevel : 1, UnlockPrice : [ "1_8000", "0_0" ], GoldAddition : [ "1_8", "0_0" ], ItemGroup : [ "10001_1", "20001_1", "20002_1", "20003_1", "20004_1", "20005_1", "20006_1" ], ItemProb : 10000, Describe : "主要产出御膳道具" 	},
		{ Id : 301, OpenLevel : 2, UnlockPrice : [ "2_2", "1_0" ], GoldAddition : [ "1_20", "0_0" ], ItemGroup : [ "30001_1", "30002_1", "30003_1", "30004_1", "30005_1", "30006_1", "30007_1", "30008_1" ], ItemProb : 10000, Describe : "主要产出御品道具" 	},
		{ Id : 302, OpenLevel : 3, UnlockPrice : [ "2_3", "1_2000" ], GoldAddition : [ "1_32", "0_0" ], ItemGroup : [ "40001_1", "40002_1", "40003_1", "40004_1", "40005_1" ], ItemProb : 10000, Describe : "主要产出服装道具" 	},
		{ Id : 303, OpenLevel : 4, UnlockPrice : [ "2_6", "1_2000" ], GoldAddition : [ "1_62", "0_0" ], ItemGroup : [ "10001_1", "20001_1", "20002_1", "20003_1", "20004_1", "20005_1", "20006_1" ], ItemProb : 10000, Describe : "主要产出御膳道具" 	},
		{ Id : 304, OpenLevel : 5, UnlockPrice : [ "2_11", "1_0" ], GoldAddition : [ "1_110", "0_0" ], ItemGroup : [ "30001_1", "30002_1", "30003_1", "30004_1", "30005_1", "30006_1", "30007_1", "30008_1" ], ItemProb : 10000, Describe : "主要产出御品道具" 	},
		{ Id : 305, OpenLevel : 6, UnlockPrice : [ "2_17", "1_0" ], GoldAddition : [ "1_170", "0_0" ], ItemGroup : [ "40001_1", "40002_1", "40003_1", "40004_1", "40005_1" ], ItemProb : 10000, Describe : "主要产出服装道具" 	},
		{ Id : 400, OpenLevel : 1, UnlockPrice : [ "2_8", "1_0" ], GoldAddition : [ "1_80", "0_0" ], ItemGroup : [ "10001_1", "20001_1", "20002_1", "20003_1", "20004_1", "20005_1", "20006_1" ], ItemProb : 10000, Describe : "主要产出御膳道具" 	},
		{ Id : 401, OpenLevel : 2, UnlockPrice : [ "2_20", "1_0" ], GoldAddition : [ "1_200", "0_0" ], ItemGroup : [ "30001_1", "30002_1", "30003_1", "30004_1", "30005_1", "30006_1", "30007_1", "30008_1" ], ItemProb : 10000, Describe : "主要产出御品道具" 	},
		{ Id : 402, OpenLevel : 3, UnlockPrice : [ "2_32", "1_0" ], GoldAddition : [ "1_320", "0_0" ], ItemGroup : [ "40001_1", "40002_1", "40003_1", "40004_1", "40005_1" ], ItemProb : 10000, Describe : "主要产出服装道具" 	},
		{ Id : 403, OpenLevel : 4, UnlockPrice : [ "2_62", "1_0" ], GoldAddition : [ "1_620", "0_0" ], ItemGroup : [ "10001_1", "20001_1", "20002_1", "20003_1", "20004_1", "20005_1", "20006_1" ], ItemProb : 10000, Describe : "主要产出御膳道具" 	},
		{ Id : 404, OpenLevel : 5, UnlockPrice : [ "2_110", "1_0" ], GoldAddition : [ "1_1100", "0_0" ], ItemGroup : [ "30001_1", "30002_1", "30003_1", "30004_1", "30005_1", "30006_1", "30007_1", "30008_1" ], ItemProb : 10000, Describe : "主要产出御品道具" 	},
		{ Id : 405, OpenLevel : 6, UnlockPrice : [ "2_170", "1_0" ], GoldAddition : [ "1_1700", "0_0" ], ItemGroup : [ "40001_1", "40002_1", "40003_1", "40004_1", "40005_1" ], ItemProb : 10000, Describe : "主要产出服装道具" 	}
	]


// Id
export var PalaceMapMaidById : game.Dictionary<table.IPalaceMapMaidDefine> = {}
function readPalaceMapMaidById(){
  for(let rec of PalaceMapMaid) {
    PalaceMapMaidById[rec.Id] = rec; 
  }
}
readPalaceMapMaidById();
}

