// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var PassLevels : table.IPassLevelsDefine[] = [
		{ Id : 1, Name : "绣女", Reward : "Image/GameScene/Pass/pass_1", NextLevels : 2 	},
		{ Id : 2, Name : "作弊", Reward : "Image/GameScene/Pass/pass_2", NextLevels : 3 	},
		{ Id : 3, Name : "泼水", Reward : "Image/GameScene/Pass/pass_3", NextLevels : 4 	},
		{ Id : 4, Name : "", Reward : "", NextLevels : 5 	},
		{ Id : 5, Name : "", Reward : "", NextLevels : 6 	},
		{ Id : 6, Name : "", Reward : "", NextLevels : 7 	},
		{ Id : 7, Name : "", Reward : "", NextLevels : 8 	},
		{ Id : 8, Name : "", Reward : "", NextLevels : 9 	},
		{ Id : 9, Name : "", Reward : "", NextLevels : 10 	},
		{ Id : 10, Name : "", Reward : "", NextLevels : 11 	},
		{ Id : 11, Name : "", Reward : "", NextLevels : 12 	},
		{ Id : 12, Name : "", Reward : "", NextLevels : 13 	},
		{ Id : 13, Name : "", Reward : "", NextLevels : 14 	},
		{ Id : 14, Name : "", Reward : "", NextLevels : 15 	},
		{ Id : 15, Name : "", Reward : "", NextLevels : 16 	},
		{ Id : 16, Name : "", Reward : "", NextLevels : 17 	},
		{ Id : 17, Name : "", Reward : "", NextLevels : 18 	},
		{ Id : 18, Name : "", Reward : "", NextLevels : 19 	},
		{ Id : 19, Name : "", Reward : "", NextLevels : 20 	},
		{ Id : 20, Name : "", Reward : "", NextLevels : 0 	}
	]


// Id
export var PassLevelsById : game.Dictionary<table.IPassLevelsDefine> = {}
function readPassLevelsById(){
  for(let rec of PassLevels) {
    PassLevelsById[rec.Id] = rec; 
  }
}
readPassLevelsById();
}

