// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Reward : table.IRewardDefine[] = [
		{ Id : 1, DropId : 11001, PropType : 1, Prop : 10000, RewardType : 7, RewardId : 1, RewardValue : 0 	},
		{ Id : 2, DropId : 12001, PropType : 1, Prop : 10000, RewardType : 2, RewardId : 0, RewardValue : 5 	},
		{ Id : 3, DropId : 13001, PropType : 1, Prop : 10000, RewardType : 1, RewardId : 0, RewardValue : 2500 	},
		{ Id : 4, DropId : 13001, PropType : 1, Prop : 10000, RewardType : 6, RewardId : 60001, RewardValue : 0 	},
		{ Id : 5, DropId : 14001, PropType : 1, Prop : 10000, RewardType : 7, RewardId : 2, RewardValue : 0 	},
		{ Id : 6, DropId : 15001, PropType : 1, Prop : 10000, RewardType : 1, RewardId : 0, RewardValue : 600 	},
		{ Id : 7, DropId : 15001, PropType : 1, Prop : 5000, RewardType : 6, RewardId : 60001, RewardValue : 0 	},
		{ Id : 8, DropId : 16001, PropType : 1, Prop : 10000, RewardType : 1, RewardId : 0, RewardValue : 1800 	},
		{ Id : 9, DropId : 16001, PropType : 1, Prop : 5000, RewardType : 6, RewardId : 60001, RewardValue : 0 	},
		{ Id : 10, DropId : 60001, PropType : 2, Prop : 20, RewardType : 5, RewardId : 0, RewardValue : 1 	},
		{ Id : 11, DropId : 60001, PropType : 2, Prop : 20, RewardType : 5, RewardId : 1, RewardValue : 1 	},
		{ Id : 12, DropId : 60001, PropType : 100, Prop : 50, RewardType : 5, RewardId : 2, RewardValue : 10 	},
		{ Id : 13, DropId : 60001, PropType : 2, Prop : 10, RewardType : 5, RewardId : 3, RewardValue : 1 	},
		{ Id : 14, DropId : 60001, PropType : 2, Prop : 20, RewardType : 5, RewardId : 4, RewardValue : 1 	},
		{ Id : 15, DropId : 20001, PropType : 2, Prop : 10, RewardType : 1, RewardId : 0, RewardValue : 1800 	},
		{ Id : 16, DropId : 20001, PropType : 2, Prop : 10, RewardType : 2, RewardId : 0, RewardValue : 1 	},
		{ Id : 17, DropId : 20001, PropType : 2, Prop : 10, RewardType : 5, RewardId : 2, RewardValue : 1 	},
		{ Id : 18, DropId : 20001, PropType : 2, Prop : 10, RewardType : 3, RewardId : 20001, RewardValue : 1 	},
		{ Id : 19, DropId : 20001, PropType : 2, Prop : 10, RewardType : 3, RewardId : 20002, RewardValue : 1 	},
		{ Id : 20, DropId : 20001, PropType : 2, Prop : 10, RewardType : 3, RewardId : 20003, RewardValue : 1 	},
		{ Id : 21, DropId : 20001, PropType : 2, Prop : 10, RewardType : 3, RewardId : 20004, RewardValue : 1 	},
		{ Id : 22, DropId : 20001, PropType : 2, Prop : 10, RewardType : 3, RewardId : 20005, RewardValue : 1 	},
		{ Id : 23, DropId : 20001, PropType : 2, Prop : 10, RewardType : 3, RewardId : 20006, RewardValue : 1 	},
		{ Id : 24, DropId : 20001, PropType : 2, Prop : 10, RewardType : 3, RewardId : 10001, RewardValue : 1 	},
		{ Id : 25, DropId : 20002, PropType : 2, Prop : 10, RewardType : 1, RewardId : 0, RewardValue : 1800 	},
		{ Id : 26, DropId : 20002, PropType : 2, Prop : 10, RewardType : 2, RewardId : 0, RewardValue : 1 	},
		{ Id : 27, DropId : 20002, PropType : 2, Prop : 10, RewardType : 5, RewardId : 2, RewardValue : 1 	},
		{ Id : 28, DropId : 20002, PropType : 2, Prop : 10, RewardType : 3, RewardId : 30001, RewardValue : 1 	},
		{ Id : 29, DropId : 20002, PropType : 2, Prop : 10, RewardType : 3, RewardId : 30002, RewardValue : 1 	},
		{ Id : 30, DropId : 20002, PropType : 2, Prop : 10, RewardType : 3, RewardId : 30003, RewardValue : 1 	},
		{ Id : 31, DropId : 20002, PropType : 2, Prop : 10, RewardType : 3, RewardId : 30004, RewardValue : 1 	},
		{ Id : 32, DropId : 20002, PropType : 2, Prop : 10, RewardType : 3, RewardId : 30005, RewardValue : 1 	},
		{ Id : 33, DropId : 20002, PropType : 2, Prop : 10, RewardType : 3, RewardId : 30006, RewardValue : 1 	},
		{ Id : 34, DropId : 20002, PropType : 2, Prop : 10, RewardType : 3, RewardId : 30007, RewardValue : 1 	},
		{ Id : 35, DropId : 20002, PropType : 2, Prop : 10, RewardType : 3, RewardId : 10001, RewardValue : 1 	},
		{ Id : 36, DropId : 20003, PropType : 2, Prop : 10, RewardType : 1, RewardId : 0, RewardValue : 1800 	},
		{ Id : 37, DropId : 20003, PropType : 2, Prop : 10, RewardType : 2, RewardId : 0, RewardValue : 1 	},
		{ Id : 38, DropId : 20003, PropType : 2, Prop : 10, RewardType : 5, RewardId : 2, RewardValue : 1 	},
		{ Id : 39, DropId : 20003, PropType : 2, Prop : 10, RewardType : 3, RewardId : 40001, RewardValue : 1 	},
		{ Id : 40, DropId : 20003, PropType : 2, Prop : 10, RewardType : 3, RewardId : 40002, RewardValue : 1 	},
		{ Id : 41, DropId : 20003, PropType : 2, Prop : 10, RewardType : 3, RewardId : 40003, RewardValue : 1 	},
		{ Id : 42, DropId : 20003, PropType : 2, Prop : 10, RewardType : 3, RewardId : 40004, RewardValue : 1 	},
		{ Id : 43, DropId : 20003, PropType : 2, Prop : 10, RewardType : 3, RewardId : 40005, RewardValue : 1 	},
		{ Id : 44, DropId : 20003, PropType : 2, Prop : 10, RewardType : 3, RewardId : 10001, RewardValue : 1 	},
		{ Id : 45, DropId : 20004, PropType : 1, Prop : 5000, RewardType : 6, RewardId : 20001, RewardValue : 1 	},
		{ Id : 46, DropId : 20005, PropType : 1, Prop : 5000, RewardType : 6, RewardId : 20002, RewardValue : 1 	},
		{ Id : 47, DropId : 20006, PropType : 1, Prop : 5000, RewardType : 6, RewardId : 20003, RewardValue : 1 	},
		{ Id : 48, DropId : 20007, PropType : 1, Prop : 3000, RewardType : 6, RewardId : 20001, RewardValue : 1 	},
		{ Id : 49, DropId : 20008, PropType : 1, Prop : 3000, RewardType : 6, RewardId : 20002, RewardValue : 1 	},
		{ Id : 50, DropId : 20009, PropType : 1, Prop : 3000, RewardType : 6, RewardId : 20003, RewardValue : 1 	},
		{ Id : 51, DropId : 20010, PropType : 2, Prop : 10, RewardType : 1, RewardId : 0, RewardValue : 1800 	},
		{ Id : 52, DropId : 20010, PropType : 2, Prop : 10, RewardType : 5, RewardId : 2, RewardValue : 1 	},
		{ Id : 53, DropId : 20010, PropType : 2, Prop : 10, RewardType : 3, RewardId : 10001, RewardValue : 1 	},
		{ Id : 54, DropId : 20011, PropType : 2, Prop : 10, RewardType : 1, RewardId : 0, RewardValue : 1800 	},
		{ Id : 55, DropId : 20011, PropType : 2, Prop : 10, RewardType : 5, RewardId : 2, RewardValue : 1 	},
		{ Id : 56, DropId : 20011, PropType : 1, Prop : 8000, RewardType : 6, RewardId : 20011, RewardValue : 1 	},
		{ Id : 57, DropId : 20013, PropType : 1, Prop : 5000, RewardType : 6, RewardId : 20011, RewardValue : 1 	},
		{ Id : 58, DropId : 20014, PropType : 1, Prop : 3000, RewardType : 6, RewardId : 20011, RewardValue : 1 	},
		{ Id : 59, DropId : 20015, PropType : 2, Prop : 10, RewardType : 0, RewardId : 0, RewardValue : 1800 	},
		{ Id : 60, DropId : 20015, PropType : 2, Prop : 10, RewardType : 3, RewardId : 10001, RewardValue : 1 	},
		{ Id : 61, DropId : 20016, PropType : 1, Prop : 8000, RewardType : 6, RewardId : 20015, RewardValue : 1 	},
		{ Id : 62, DropId : 20017, PropType : 1, Prop : 5000, RewardType : 6, RewardId : 20015, RewardValue : 1 	},
		{ Id : 63, DropId : 20018, PropType : 1, Prop : 3000, RewardType : 6, RewardId : 20015, RewardValue : 1 	},
		{ Id : 64, DropId : 30001, PropType : 1, Prop : 10000, RewardType : 1, RewardId : 0, RewardValue : 1800 	},
		{ Id : 65, DropId : 30001, PropType : 1, Prop : 3000, RewardType : 6, RewardId : 60002, RewardValue : 1 	},
		{ Id : 66, DropId : 30002, PropType : 2, Prop : 10, RewardType : 1, RewardId : 0, RewardValue : 7200 	},
		{ Id : 67, DropId : 30002, PropType : 2, Prop : 10, RewardType : 1, RewardId : 0, RewardValue : 7500 	},
		{ Id : 68, DropId : 30002, PropType : 2, Prop : 10, RewardType : 1, RewardId : 0, RewardValue : 6400 	},
		{ Id : 69, DropId : 30002, PropType : 2, Prop : 10, RewardType : 1, RewardId : 0, RewardValue : 6900 	},
		{ Id : 70, DropId : 30003, PropType : 2, Prop : 10, RewardType : 1, RewardId : 0, RewardValue : 1800 	},
		{ Id : 71, DropId : 30003, PropType : 2, Prop : 10, RewardType : 1, RewardId : 0, RewardValue : 2000 	},
		{ Id : 72, DropId : 40001, PropType : 1, Prop : 5000, RewardType : 1, RewardId : 0, RewardValue : 1800 	},
		{ Id : 73, DropId : 40001, PropType : 1, Prop : 5000, RewardType : 4, RewardId : 0, RewardValue : 1 	}
	]


// Id
export var RewardById : game.Dictionary<table.IRewardDefine> = {}
function readRewardById(){
  for(let rec of Reward) {
    RewardById[rec.Id] = rec; 
  }
}
readRewardById();
}

