// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Reward : table.IRewardDefine[] = [
		{ Id : 1, DropId : 1, PropType : 3, Prop : 1, RewardType : 1, RewardId : 10, RewardValue : 1 	}
	]


// Id
export var RewardById : game.Dictionary<table.IRewardDefine> = {}
function readRewardById(){
  for(let rec of Reward) {
    RewardById[rec.Id] = rec; 
  }
}
readRewardById();
}

