// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Travel : table.ITravelDefine[] = [
		{ Id : "1_2_0", Event : 1001 	}
	]


// Id
export var TravelById : game.Dictionary<table.ITravelDefine> = {}
function readTravelById(){
  for(let rec of Travel) {
    TravelById[rec.Id] = rec; 
  }
}
readTravelById();
}

