// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var Travel : table.ITravelDefine[] = [
		{ Id : "30001_20001_40001", Event : 1001 	},
		{ Id : "30001_0_0", Event : 1003 	},
		{ Id : "30002_0_0", Event : 1002 	},
		{ Id : "30003_0_0", Event : 1003 	},
		{ Id : "30004_0_0", Event : 1002 	},
		{ Id : "30005_0_0", Event : 1003 	},
		{ Id : "30006_0_0", Event : 1002 	},
		{ Id : "30007_0_0", Event : 1003 	},
		{ Id : "30008_0_0", Event : 1003 	},
		{ Id : "0_20001_0", Event : 1002 	},
		{ Id : "0_20002_0", Event : 1003 	},
		{ Id : "0_20003_0", Event : 1002 	},
		{ Id : "0_20004_0", Event : 1003 	},
		{ Id : "0_20005_0", Event : 1003 	},
		{ Id : "0_20006_0", Event : 1002 	},
		{ Id : "0_0_40001", Event : 1003 	},
		{ Id : "0_0_40002", Event : 1003 	},
		{ Id : "0_0_40003", Event : 1002 	},
		{ Id : "0_0_40004", Event : 1003 	},
		{ Id : "0_0_40005", Event : 1002 	}
	]


// Id
export var TravelById : game.Dictionary<table.ITravelDefine> = {}
function readTravelById(){
  for(let rec of Travel) {
    TravelById[rec.Id] = rec; 
  }
}
readTravelById();
}

